### ISSUE TITLE
[Team 7] Boss Mobs

### ISSUE THREAD

**Issue by ThivanW** [UQcsse3200/2023-studio-3#10]
# **Description**
We plan on making two different types of boss mobs in order to raise the difficulty in later waves in the game. The bosses will have unique features that separate them from the general mobs that usually appear. The bosses like the other mobs will move towards the humans and attack towers that they come in contact with.

## SubFeature/component (optional)
The first boss mob will move two tiles and then stop and do a ranged attack before moving again.
The final boss mob will switch lanes every few seconds, have more health and be slower than a general mob.

# **Dependencies**
A lot of the base features for boss mobs will overlap with the general mobs (#4) implementation. As such, similarly to general mobs the boss mobs will depend on tower features (#5) and the map features.

# **Milestones**
- [x] Movement for the first boss (Aug. 21)
- [x] Movement for the final boss (Aug. 23) #20 
- [x] Collision between the bosses and towers (Aug. 25)
- [x] #24
- [x] Boss spawning (Aug. 24)
- [ ] Reaching the ship with the boss (Aug. 28)
- [ ] Boss damaged (Aug. 23)
- [ ] Boss death (Aug. 27)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Boss mobs animations (Aug. 27)
- [ ] Boss sounds (Aug. 29)

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
Thivan (@ThivanW) (Thivan Wijesooriya)
Ken (@lenhatminh451) (Ken Le)
Sai (@karthikeya-v) (karthik)
Yelmela (@Vishal-jodd) (Yelmela Vishal)
Deven (@dbhasin4123) (Deven)

**Comment by Jonoym** [comment]
The feature ticket looks good. Expanding out some of the milestones and what would be required to complete them in the form of a task ticket would be great as well.
