### ISSUE TITLE
[Team-3] Maps Grid & Lanes

### ISSUE THREAD

**Issue by aadityayadav17** [UQcsse3200/2023-studio-3#100]
# **Description**
**Task:** Grid & Lanes.
**Feature:** [Maps Feature Ticket (Sprint-2)](#73)

The task is fixing the grid, adjusting its boundaries, and realigning the lanes to ensure their heights are consistent.
 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Fix the number of tiles with respect to the grid (Sept. 2)
- [x] Reset the grid boundaries (Sept. 4)
- [x] Fix lane heights in accordance to mob & tower heights (Sept. 6)
 
**Completion Deadline:** Sept. 9

# **Documentation**
- [Game Screen](../wiki/Game-Screens)
- [Game Area](../wiki/Game-Areas)

# **Members**
-  Gagandeep ( @Gaganx0 ) (Gagandeep Singh)
-  Nidhi ( @Nidhidass1 ) (Nidhi Dass)
-  Aaditya ( @aadityayadav17 ) ( Aaditya Yadav)
