### ISSUE TITLE
[Team-3] Lane implementation(mob specific) and map array

### ISSUE THREAD

**Issue by Octagunn** [UQcsse3200/2023-studio-3#101]
# **Description**
**Task:** [lanes](#3).
**Feature:** [Maps Feature ticket ](#40 )

task is concerned with the creation and implementation of the lanes and its subsequent mechanics in the game area and terrain aling with the implementation of a specific lane in the map

# **Dependencies**

- Dependency 1 (#78 )

e.g.
-  to add a specific lane or lanes that work in a way that restricts movement of character inside the lane

# **Milestones**
List of steps that need to be completed for this task.
- [x] creation and implementation of lanes (Sept. 7)
- [x] creation of additional lanes with specific conditions(engineer that follows the mc) (Sept. 9)
- [x] fixing / cleanup of map grid in relation of lanes (sept. 10)
- [x] Create an 2-d array so towers can be placed into them

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Rakshit Nandal (@Octagunn ) (Rakshit)
- Gagandeep Singh (@Gaganx0 )(Gagandeep Singh)
