### ISSUE TITLE
[Team-3] New level

### ISSUE THREAD

**Issue by Gaganx0** [UQcsse3200/2023-studio-3#105]
# **Description**
**Task:** [Create a new level].
**Feature:** [Maps](#73 )

Create a new level, with different background, and where other teams could implement level specific spawning methods and towers.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] create new game screen (Sep.8)
- [x] create a trigger to go to the next level(Sep.9)
- [x] Integrate both the steps(Sep.10)
 
**Completion Deadline:** Sep.12

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)

 
# **Member**
- Gagandeep( @Gaganx0 ) (Gagandeep)
