### ISSUE TITLE
Start Screen- Team : 6

### ISSUE THREAD

**Issue by ElanagaiArivuchelvan** [UQcsse3200/2023-studio-3#107]
# **Description**
**Task:** [Updated game name with background png](#3).
**Feature:** [Features](#2)

The start page of the game immerses players in a visually stunning and captivating space-themed background.
At the center-top of the start page, the game's title"Outworld Outposts" is prominently displayed. The logo is sleek and futuristic, with horror and fright inspired fonts that reflect the game's theme of fights

# **Dependencies**

This task involved updating and removing the background colour team 6 implemented for sprint 1 , Referencing to ticket #36 

- [ ] @design commitee (To ensure that the background makes sense with the overall UI )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] remove the  escape earth logo and the background colour (Aug 30)
- [x] decide with the map team regarding the resolution and pixel issues of the Png (sep 1)
- [x] Change the background of the Start page to the desired Png  (sep 2)
- [x] Design and implement the title of the game according to the background image pallet ( sep 5)
- [x] test to see if the game is not crashing (as this was a problem faced in Sprint 1)  (sep 5)
 
**Completion Deadline:** sep 6

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- e.g. Rahul Sagar Pabba ( @rahulsagar500 )

**Comment by ElanagaiArivuchelvan** [comment]
done!
