### ISSUE TITLE
Drag and drop dialogue box - Team 6

### ISSUE THREAD

**Issue by ElanagaiArivuchelvan** [UQcsse3200/2023-studio-3#108]
# **Description**
**Task:** [Drag and drop display box ](#3).
**Feature:** [Features](#2)

Creating a display box to place different options in a game is a common user interface design element that allows players to interact with various in-game choices or settings. In context to our game this box would contain the types of towers so that the user is allowed to drag and place the towers in the map to be able to facilitate the game play.

# **Dependencies**

- [ ] @design commitee (#xx)
- [ ] Map team so that the positioning is deemed perfect (@team3)
- [ ] the tower team so that the actual types of towers are given to be put it up on the screen ( @team2) 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create the dialogue box in the game screen ( sep 2 )
- [x] insert the different images of the towers to the display screen for the user to select( sep5)
- [x] position the tile in the game lanes accordingly so that after a tower is selected it doesn't disrupt the whole 
       display box design ( sep 8)
- [x] Test and Intergrate( sep 8)
 
**Completion Deadline:** Sep 8

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
-  Vansh Mittal (@V4N5HM)

**Comment by ElanagaiArivuchelvan** [comment]
The different types of tower are displayed at the top of the screen so that the user can choose one to input in his game play
