### ISSUE TITLE
Drag and Drop mouse Input

### ISSUE THREAD

**Issue by ElanagaiArivuchelvan** [UQcsse3200/2023-studio-3#109]
# **Description**

Implementing a drag-and-drop mouse input feature in a game allows players to interact with in-game objects, elements (towers here) by clicking and dragging them using the mouse cursor.
In this implementation the player should be able to drag a tower of his choice from the towers display box and place in in the game screen to facilitate his game play 

# **Dependencies**

- [ ] tower team for the data input on the types of tower  (team2)
- [ ] implementation of the display box for the dragging option ( #108 )

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] implementing the one mouse function among the 7 functions to be able it click in the display box , preferably 
       the function input (sep 8)
- [ ] implementing the second mouse function to be able to drag the tower from the display box (sep 9)
- [ ] positioning and spawing of the tower according to the user selection (sep 9)
- [ ] test by implementing and play many positing of towers  (Sep 10)

**Completion Deadline:** sep 11

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**

-  Jigyasu mittal (@JigyasuMittal)
-  Rahul Sagar Pabba (@rahulsagar500)

**Comment by The-AhmadAA** [comment]
This ticket closed, feature implemented in #207
