### ISSUE TITLE
[Team 2] User tower interaction

### ISSUE THREAD

**Issue by AlasdairS4698737** [UQcsse3200/2023-studio-3#11]
# **Description**
**Task:** [Tower pop-up inplementation](#3).
**Feature:** [Tower feature ticket](#5)

The task involves implementing the ways the player can interact with towers once they have been placed down. This will be done in the form of a pop-up that appears when the player clicks on a turret that has been placed, and vanish when a second click is done outside the pop-up menu. The pop-up will show the tower's statistics. The statistics give the amount of health the tower has, and if it has the capability to attack aliens, its fire rate and damage per shot.

## **Future Features**
Once basic functionality is successfully implemented, the following avenues are considered for additional features:
- **Aesthetic**: The pop-up menu will be redesigned to fit the aesthetic appearance of the tower build menu more closely.
- **Repair**: The menu will contain a button to spend a small amount of money to repair some missing HP from the tower.
- **Selling**: The menu will contain a button to delete the tower, partially refunding the cost to build it.
- **Upgrading**: The menu will contain some buttons to upgrade the tower, spending money to improve it's statistics or add a new effect.

## **Example**
- **End Functionality**: Once a tower has been placed, players will be able to click on it to bring up a menu. In this menu, they will be able to determine the tower's health, including how much damage it has sustained, get an option to repair damage if it has taken any, get an option to sell the tower to get a partial refund on its cost, and have a set of upgrades they can buy to make the tower better. Clicking off the menu will close the pop-up menu.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Tower needs to be placed before it can be selected (#06)

Dependencies for future features:
- [ ] UI designs of tower placement menu, so tower selection pop-up can match the aesthetic (Team 6)
- [ ] In game cash increases/decreases for selling/upgrading/repairing the tower (Team 5)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design a basic tower menu pop-up (Aug. 20)
- [ ] Implement input handling functionality, so the system can detect when the user clicks, and if they clicked a tower (Aug. 23)
- [ ] Implement the system for creating a pop-up menu when a tower is clicked on (Aug. 25)
- [ ] Implement the system for deleting the pop-up menu when the user clicks outside the menu (Aug. 26)
- [ ] Testing and documentation of the implemented tower interaction menu and its associated mechanisms (Aug. 28)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Alasdair Sinclair (@AlasdairS4698737) (Alasdair Sinclair)

**Comment by Jonoym** [comment]
@AlasdairS4698737 This task looks great! Don't forget to assign yourself (and any other team members) and add projects and milestones.

**Comment by AlasdairS4698737** [comment]
This task has been taken up by (#34), as their feature scope covers the creation of a tower interactive menu.

**Comment by The-AhmadAA** [comment]
Majority of this task taken up by other teams.
