### ISSUE TITLE
[Team 5] Level selection

### ISSUE THREAD

**Issue by ryandmcneilly** [UQcsse3200/2023-studio-3#111]
# **Description**
**Task:** [Level selection](#111)
**Feature:** [UI](#96 )
After starting the game, the user will be prompted to choose a level (this will be a planet). The user would be prompted with a screen showing different planets which the user can click on to choose a level. Currently, only the starting planet will be available, the rest will be locked out for this sprint.

## Sub Features/Component 
Each member will be responsible for one of the following components:
- Outline of the planet when hovering over it
- Click the planet then the appropriate level will be loaded

 
# **Dependencies**
This ticket has no dependencies.

# **Milestones**
#### Goal 1 (Sep 8): Planning and Scaffolding 
- [x] Design of level screen
- [x] Abstract classes required
#### Goal 2 (Sep 10) Code Implementation and Test Design (JUnit)
- [x] Implementation of Level screen 
- [x] Test suite
#### Goal 3 (Sep 12) Documentation
- [x] Documentation of technologies and level classes implemented

**Completion Deadline:** Sep 12

# **Documentation**
TBD

# **Members**
Ryan (@ryandmcneilly) (Ryan McNeilly)
Nawal (@nawal-0) (Nawal)

**Comment by The-AhmadAA** [comment]
Great work so far! Just wondering if you guys could slow down the planet spin in the level select screen? It seems quite fast at the moment.
