### ISSUE TITLE
Team 5 - Turret Picking Menu and Game Start "Lore" Screen

### ISSUE THREAD

**Issue by Hasakev** [UQcsse3200/2023-studio-3#112]
# **Task Ticket: Turret Picking Menu and Game Start "Lore" Screen**

**Task:**  Turret Picking Menu and Game Start "Lore" Screen
**Feature:** #96 

## **Description**
This task will implement two components:
1. A screen that displays the starting lore of the game.
2. The turret picking menu loads in after the game "lore" screen and allows the user to pick a turret from the assortment of all turrets.

## **Dependencies**
- In terms of UI, we will need to work closely with Team 6 to avoid clashing.
- We will need to cooperate with Team 2 for the turret types.
- Communicate with design committee for design choices.
- No issue dependencies.

## **Milestones**
List of steps that need to be completed for this task.

#### Goal 1 (Sep 6): Planning and Scaffolding 
- [x] Plan out design of turret picking menu and game start screen
> Since this feature planned out quite late (08/09), we will create a UI with limited design choices and consult with the design committee next sprint.
- [x] Design and plan the implementation of the two screens

#### Goal 2 (Sep 8) Code Implementation and Test Design (JUnit)
- [x] Implement turret picking menu
- [x] Implement game start screen
- [x] Write JUnit tests for the screens (ensure use of mocking)

#### Goal 3 (Sep 10) Testing and Debugging; Integration
- [x] Communicate with other teams for integration
- [x] Test screens with other features from other teams for bugs and issues

#### Goal 4 (Sep 11) Documentation
- [x] Document the implementation details of the screens
- [x] Update relevant documentation to reflect the changes made.

**Completion Deadline:** Sep. 12

> If time is still available, improve the currency classes i.e. animations and bugfixes

## **Documentation**
- TBA

## **Member**
- Kevin (@Hasakev) (Kevin Luo)
- Jackie (@fattyhope) (Jackie)
