### ISSUE TITLE
Tower stats

### ISSUE THREAD

**Issue by ElanagaiArivuchelvan** [UQcsse3200/2023-studio-3#113]
# **Description**
**Task:** [Displaying the tower stats in s pop up box](#3).
**Feature:** [Feature](#2)

A tower statistics pop-up feature in a game is a user interface element that provides players with detailed information about a tower, structure, or defensive unit in a tower defence or strategy game. This feature allows players to make informed decisions about their gameplay strategy, including upgrading and  placing towers effectively. which overall decides and changes the game play.
 

# **Dependencies**

- [ ] Design committee for the bending of all design of texts and boxes (@designcommitee)
- [ ] Tower input for the currency and health and all the data (@team2)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] get the enitity to be upgraded (Sep 2)
- [ ] triggering an event for the user input ( sep 4)
- [ ]  upgradation and health stats retrieval ( sep 6)
- [ ] designing the display box and the fonts ( sep 7)
- [ ]  implementing the cursor function to be able to have the display box when scrolled over every tower 
        ( sep 10)        
- [ ]  test and integrate ( sep 11)

 
**Completion Deadline:** Sep 11
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Elanagai Arivuchelvan (@ElanagaiArivuchelvan)
-  Sahajdeep Singh (@sahajdeep)

**Comment by The-AhmadAA** [comment]
This ticket closed as this feature implemented in #188
