### ISSUE TITLE
[Team 1] Extend single-target projectiles to have multi-target projectiles

### ISSUE THREAD

**Issue by JSLLW** [UQcsse3200/2023-studio-3#12]
# **Description**
**Task:** [Extend single-target projectiles to have multi-target projectiles](https://github.com/UQcsse3200/2023-studio-3/issues/12#7) 
**Feature:** [Projectiles](https://github.com/UQcsse3200/2023-studio-3/issues/7)

Implements multiple projectiles. This will produce multiple single-target projectiles from the same starting point towards different directions. May inherit from a projectile class or may be a means to produce multiple of the same projectile with the same starting point but different end point. The number of projectiles will be an adjustable field. The angles between projectiles will be adjusted accordingly to compensate. Another field that may be relevant for this task is being able to select the type of projectile if extras are implemented. May adjust speed of the projectiles to be slower than normal single projectile.

# **Dependencies**
- [x] Single-target Projectiles need to be implemented to an extent for testing multi projectileS (#8)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Duplicating projectiles (Aug. 20)
- [x] Adjusting angles between projectiles (Aug. 23)
- [x] Adjusting the amount of projectiles (Aug. 25)
- [x] Documentation of [Multi-target Projectiles](../wiki/Multi‐target-Projectiles) updated on wiki (Aug. 26).

**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Main description of feature](../wiki/Game-Features)
- [User documentation](../wiki/User-Documentation)
 
# **Member**
- Jo Wong (@JSLLW) (s4528565@student.uq.edu.au)
- Isaac Arli (@MiniSoda17) (Isaac Arli)
