### ISSUE TITLE
[Team 5] - Refining Economy

### ISSUE THREAD

**Issue by nawal-0** [UQcsse3200/2023-studio-3#121]
# **Description**
**Task:** Refining Economy (#121).
**Feature:** UI (#96 )

This task is to refine aspects of the economy system which was implemented in sprint 1. This involves updating images/UI, of the currency display and income turret, to be in accordance with the new guidelines set by the design committee. Also, when a drop is clicked, the player should receive some visual feedback and sound that they have gained currency. 
A new currency class is to be instantiated for the mob bosses drop.

# **Examples**
- **Visual Feedback**: When a drop is clicked or the income turret 'mines', a label '+100' or similar shows up
 
# **Dependencies**
No dependencies
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a new currency class. Add it to the CurrencyService and make a function in the dropFactory (Sep 8)
- [x] Implement the visual feedback function to show a label when a drop is clicked (Sep 8)
- [x] Extend it so that when income turret mines, the label also appears (Sep 9)
- [x] Add sound (Sep 10)
- [x] Documentation (Sep 10)
 
**Completion Deadline:** Sep 10
 
# **Documentation**
- [Main description of feature](../wiki/Currency)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Nawal (@nawal-0) (Nawal)
