### ISSUE TITLE
[Team 1] AOE Projectiles

### ISSUE THREAD

**Issue by gregchan550** [UQcsse3200/2023-studio-3#13]
# **Description**
**Task:** AOE Projectiles(#13).
**Feature:** Projectiles(#2)

Implementing the base mechanics for AOE (area of effect) projectiles. This class will inherit from the projectiles class. It will therefore have a hitbox and be able to collide with mobs and other objects in the game along with speed, direction and other variables to be implemented. The AOE projectiles will have a multiplier for different types of projectiles so that different sizes of effects can occur.
 
## **Example (optional)**
- **Rocket Projectile**: A rocket projectile may have an AOE multiplier of 2 which means that once it collides with a mob, along with doing damage to the mob on that tile, it will also do damage to the tiles directly above, below and behind.

# **Dependencies**
- [x] Collisions need to be created for the projectile to have a hitbox and for #8 to be created (#collisions)
- [x] Single-Target-Projectiles need to be created so the base mechanics for the AOE class can be inherited. (#8 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial design of 'AOE' created and documented on wiki (Aug. 19)
- [ ] Unit tests implemented for 'AOE' (Aug. 23)
- [x] Have 'AOE' fully functional and updated on the wiki (Aug. 25)
 
**Completion Deadline:** Aug. 25
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Gregory Chan (gregchan550) (Gregory)
