### ISSUE TITLE
Collaboration Team 2/Team5- End Game Loss State

### ISSUE THREAD

**Issue by The-AhmadAA** [UQcsse3200/2023-studio-3#132]
# **Description**
**Task:** End Game Loss State
**Feature:** [Engineers Feature](#80)

This task proposes to implement the tracking and triggering infrastructure for end-game loss state, linked closely to the Engineers Feature. This will involve the creation of a service to track the number of engineer entities killed, and trigger the loss state if the engineer death limit is reached.

# **Dependencies**
Not strict dependencies per se, but links to end game screens and to the engineers feature
- [x] [End Game Screens](#94)
- [x] [Engineers Feature](#80)
 
# **Milestones**

- [x] Creation of GameEndService
- [x] Integration of GameEndService
- [x] Implementation of engineer death tracking
- [x] Triggering game loss
- [x] Documentation of GameEndService updated on wiki
- [ ] ~~JUnit Test written~~ JUnit test not used, this is heavily tied in to UI elements and is simple enough that it was felt it could be sufficiently tested manually.
 
**Completion Deadline:** Sep. 11

# Optional/Future tasks
 
- [x] Addition of UI element to track Engineer Count

# **Documentation**
- [GameStateService](Game-State-Service)
 
# **Member**
- Ahmad(The-AhmadAA) (Ahmad Abu-Aysha)
- Nawal (nawal-0)
