### ISSUE TITLE
[Team 1] Projectile Interactions With Enemies

### ISSUE THREAD

**Issue by freshc0w** [UQcsse3200/2023-studio-3#14]
# **Description**
**Task:** [Handle Projectile-Enemy based interaction (Collision)](#14).
**Feature:** [Projectiles](#7)

This task revolves around the implementation of the projectile-enemy based interactions and collision mechanisms within the defense game. This will be parent class that houses the `Projectile ` object, allowing adaptable and flexible interactions between other entities. The goal is to ensure that launched projectiles accurately collide with enemy entities while considering hitbox calculations. Additionally, the task also deals with the mechanics for the damage dealt and/or effects applied upon collision.
 
## **Example**
- **Projectile-Enemy Interaction**: After firing a projectile from a tower, the projectile will travel in a linear fashion. Upon hitting another entity that is classified as an 'enemy', the projectile's collision mechanism will ensure it accurately hits the enemy. This will trigger a series of events, such as dealing a set amount of damage to the specified entity. (Possibly apply status effects like slowing or burning..) 

# **Dependencies**

- [x] Defining projectile hitbox dimensions (#8)
- [x] Defining enemy mob's hitbox dimensions (#4)
- [x] Defining boss mob's hitbox dimensions (#10)
- [x] Determining enemy damage calculation logic (#4 & #10)
- [x] Considering misc dampening effects with splash effect (#13)
 
# **Milestones**
- [x] Collaborate with mob teams and single-projectile team to determine hitboxes. (Aug. 15)
- [x] Design and implement the Projectile-enemy collision logic (Aug. 20)
- [x] Testing finished for 'isColliding' mechanism with various projectile speeds and different hitboxes. (Aug. 23)
- [x] `Collision` class designed and implemented. Also develop and instantiate default "enemies" and "friendly" entities. e.g. Projectiles shot from towers shouldn't affect other towers. (Aug. 24)
- [x] Junit tests implemented for `Collision` with "friendly" and "enemy" entities. (Aug 25).
- [x] Finish testing and documentation for collision. (Aug 27).
 
**Completion Deadline:** Aug. 27
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Chia-Chuan Tsou (@freshc0w) (Chia-Chuan Tsou)
