### ISSUE TITLE
[Team 5] UI design for currency and currency generating turret

### ISSUE THREAD

**Issue by SonjaMcNeilly** [UQcsse3200/2023-studio-3#16]
# **Description**
**Task:** [UI design for currency and income generating turret](#16).
**Feature:** [Economy](#15)

This task revolves around the design of the currency that the game will use. This will include the look of the currency in the HUD, when a mob drops currency, and the currency generating turret.

# **Dependencies**

- [x] Turret UI completion for consistent UI (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] General design of currency and currency generating turret completed (Aug. 20)
- [x] Solidify Design (Aug. 26)
 
**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Sonja McNeilly (@SonjaMcNeilly ) (Sonja)
