### ISSUE TITLE
[Team-3] UI Feature Ticket (Sprint-3) 

### ISSUE THREAD

**Issue by Gaganx0** [UQcsse3200/2023-studio-3#164]
# **Description**

During this sprint, we'll improve the main menu and settings menu, functionalize the help button, align buttons with the Design Committee's guidelines, and integrate sound effects. We'll introduce a story screen, a universal exit button, and level lock animations. Additionally,  an Asset Loader class will be added to make asset organization easier. If possible also include customizable controls.

### Design: 

- Dynamic Background - Main Menu Screen, Settings Screen
- Change buttons according to Design Committee Guidelines 
- Customize the cursor 

### Functionality: 

- Make the Help Button Functional on the Main Menu Screen 
- Add Asset Loader
- Add a Universal Exit Button
- Add Skip Button to Story Screen

### Animation & Visual Effects: 

- Add Sound effects for the buttons 
- Add loading animation
- Add level Switch Animation

### Gameplay & Story: 

- Add Story Screen

# **Dependencies**

- Collaborate with the towers team for turret screen selection and visuals 

# **Milestones**

- [x] Background for Main Menu and Settings Screen (Sept. 18)
- [x] Customize the cursor (Sept. 18)
****
- [x] Change buttons according to Design Committee Guidelines (Sept. 21)
- [x] Add Sound effects for the buttons (Sept. 21)
****
- [x] Add loading animation (Sept. 24)(code written, **implementation - TODO sprint 4**)(**edited**)
- [x] Add a Universal Exit Button (Sept. 24)
****
- [x] Add Asset Loader (Sept. 27)
- [ ] Add level Switch Animation( Sept. 27)(Change of Plan)
****
- [x] Add Story Screen (Sept. 30)
- [x] Add Skip Button to Story Screen (Sept. 30)
- [x] Make the Help Button Functional on the Main Menu Screen (Sept. 30)

**Completion Deadline:** Sept.30

# **Extras (optional)**
 Customizable Controls
 Edit lose screen

# **Documentation**
- [UI](../wiki/UI)
- [Animations](../wiki/Animations)
- [Settings](../wiki/Settings)

# **Members**

- Gagandeep ( @Gaganx0 ) (Gagandeep Singh)
- Nidhi ( @Nidhidass1 ) (Nidhi Dass)
- Aaditya ( @aadityayadav17 ) ( Aaditya Yadav)
- Moksh ( @Moksh-Mehta7 ) ( Moksh Mehta)
- Rakshit ( @Octagunn ) (Rakshit)
