### ISSUE TITLE
[Team 3] Cursor customization, button texture change and pause/resume button addition

### ISSUE THREAD

**Issue by Moksh-Mehta7** [UQcsse3200/2023-studio-3#165]
# **Description**
**Task:** Combine Customize the cursor, Change buttons according to Design Committee Guidelines, and Add Pause & Resume Button tasks.

**Feature:** UI #164 

This task involves enhancing the user interface of the application by customizing the cursor, changing buttons to align with the Design Committee Guidelines, and adding a Pause & Resume Button The buttons will be updated to match the design guidelines, ensuring consistency and aesthetics.

## **Dependencies**
 Design Committee Guidelines review 

# **Milestones**
List of steps that need to be completed for this task.

**Cursor:**
- [x] Implementing the code for Custom Cursor (Sept. 17)
- [x] Adding Design of Custom Cursor (Sept. 18)

**Buttons(universal):**
- [x] Create a method to implement button texture universally(Sept. 20) 
- [x] Update buttons according to Design Committee Guidelines (Sept. 21)

**Completion Deadline:** Sept. 30

# **Documentation**
- [UI](../wiki/UI)
- [Animations](../wiki/Animations)
- [Settings](../wiki/Settings)

# **Members**
- Moksh (@Moksh-Mehta7 ) (Moksh Mehta)

**Comment by The-AhmadAA** [comment]
This issue is out of scope for external UI, this falls under in-game UI #170

**Comment by Moksh-Mehta7** [comment]
> This issue is out of scope for external UI, this falls under in-game UI #170

Ok, we will accommodate the changes
