### ISSUE TITLE
[Team-3] Loading, Help Button and AssetLoader

### ISSUE THREAD

**Issue by Gaganx0** [UQcsse3200/2023-studio-3#166]
# **Description**

**Task:** Add loading animation, AssetLoader  and Make the Help Button
**Feature:** UI #164 

Add a loading animation, a rotating circle after a planet is clicked. The Asset Loader class will be created to clean up the ForestGameArea class and make it easier to organize assets. The help button in the menu screen will be made to have a summary of all the controls of the game through images. 

# **Dependencies**

- All teams can provide a summary of their game controls so that it can be compiled into the help button. 

 
# **Milestones**

**loading animation:**
- [x] Decide on the loading animation (Sept. 21)
- [x] Write the code for the animation (Sept. 24)(**TODO- implement the code, sprint 4**) (**edited**)

**Asset Loader** 
- [x] Implement the code for the class (Sept. 27)

**Help button:**
- [x] Collect the info and images from all teams that need to be added to the help button - (Sept. 25) 
- [x] Decide upon the layout for the help screen (Sept. 26)
- [x] Create a new screen and link it to the help button (Sept. 28)
- [x] Add all collected elements onto the help screen (Sept. 30) 

 
**Completion Deadline:** Sept. 30

 
# **Documentation**
- [UI](../wiki/UI)
- [Animations](../wiki/Animations)

 
# **Member**
- Gagandeep ( @Gaganx0 ) (Gagandeep Singh)
