### ISSUE TITLE
[Team-1] Mobs Enhancement Feature 

### ISSUE THREAD

**Issue by MiniSoda17** [UQcsse3200/2023-studio-3#167]
# **Description**
For this sprint, our team will be working on improving and adding to the already-made Mobs and mob bosses within the game. For improvements, we will be fixing the animation bugs in general mobs and finishing off the animations for the already deployed mob bosses. On top of this, we will be adding much more variety of mobs to the game from general mobs to mob bosses. We will have one new general mob shooting a different projectile and have them be similar themes to their planets. In addition, we will also have one mob boss per planet with a unique ability.

### General Mobs Variation - @freshc0w 
Will be adding the cloning/splitting mobs and mobs that will steal towers instantly.

### General Mobs Design, Design & Collision Effects - @MiniSoda17
Adding the design and animation of all general mobs within the game. Also will include the the collision effects of all mobs. 

### Mob Boss Design & Animation - @cindyle1 
Adding the design and animation of all Mob Bosses within the game

### [Mob Boss Base Functionality](https://github.com/UQcsse3200/2023-studio-3/issues/177) - @JSLLW 
Clean up code for BossKingFactory and creating a mob boss that has a high health value and can wipe out a tower or engineer in one shot.

### FireBall Mob Boss - @gregchan550 
Creating the FireBall mob boss

## **Examples (optional)**
- **Cloning/Splitting Mobs**: Will split off into multiple mobs after every few seconds or when it gets hit
- **Collision Effects**: Will show that mobs are being either hit, slowed or stunned.

# **Dependencies**

e.g. New general mob designs and animations depend on the new mob projectiles (Ticket does not exist yet).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Finalise all mob bosses designs 
- [x] Finalise all general mob designs
- [x] New Mob Kings
- [x] New General Mobs
- [x] Design and animations for general mobs
- [x] Sound effects for mobs
- [x] Junit Testing for general mobs and mob bosses.

**Completion Deadline:** Oct. 03

# **Extras (optional)**
- [ ] Feet giant
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Isaac Arli (@MiniSoda17) (Isaac Arli)
- Chia-Chuan Tsou (@freshc0w ) (Chia-Chuan Tsou)
- Wing Yan Lee (@cindyle1 ) (Cindy)
- Gregory Chan (@gregchan550) (Gregory)
- Josephine Wong (@JSLLW ) (s4528565@student.uq.edu.au)
