### ISSUE TITLE
[Team-3] Exit Button, BG Music and Button Sound Effects.

### ISSUE THREAD

**Issue by Gaganx0** [UQcsse3200/2023-studio-3#168]
# **Description**

**Task:** Add a Universal Exit Button, and Sound effects for all the buttons. 
**Feature:** [UI](#164)

Currently, there is no exit button present on screens like Planet Select and Turret Select screen, so add an exit button and integrate it with the resume/pause button(#165). Also, add sound effects to the buttons with variations in placing the mouse on the button and clicking it and different types of sounds matching to the action that the button performs(e.g. contrasting sounds for start and exit buttons), also add background music to the main menu, with variations in the help menu and settings menu. 

# **Dependencies**

Design committee for music and sound effects approval.

 
# **Milestones**

**Sound Effects:**
- [x] Decide various Sound effects for different types of buttons (Sept. 19)
- [x] Implement the sound effects (Sept. 21)

**Exit Button:**
- [x] create a Universal Exit Button and keyboard key(Esc.) (Sept. 22)
- [x] Integrate the exit button with the pause/resume menu (Sept. 23)
- [x] Decide the positioning of the button and implement it (Sept. 24) 

**Completion Deadline:** Sept. 30

 
# **Documentation**
- [UI](../wiki/UI)

# **Member**
Nidhi ( @Nidhidass1 ) (Nidhi Dass)
