### ISSUE TITLE
[Team 7] First Boss Movement And Collision

### ISSUE THREAD

**Issue by ThivanW** [UQcsse3200/2023-studio-3#17]
# **Description**
**Task:** [First boss movement and collision](#17).
**Feature:** [Boss Mobs](#10)

The first boss will be more difficult than a general mob and will move in a linear path to the ship. Every few tiles that it passes by the boss will stop moving in order to make a ranged attack before resuming its movement. Upon hitting a tower the boss will stop moving. 

# **Dependencies**
- [x] The first boss's speed will be slower than a general mob's speed (#xx)
- [x] The first boss will stop moving once it collides with a tower (#6)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] The boss moves forward at a constant speed (Aug. 19)
- [x] The boss moves forward a few tiles, stops and then resumes movement (Aug. 20)
- [x] The boss stops moving when it hits a tower (Aug. 23)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Thivan (@ThivanW) (Thivan Wijesooriya)
