### ISSUE TITLE
[Team 2] In-game UI and sounds feature ticket.

### ISSUE THREAD

**Issue by shiv-0831** [UQcsse3200/2023-studio-3#170]
# **Description**
During this sprint, our primary objective will be enhancing the in-game user interface (UI) and incorporating new audio elements to enhance the game's overall appeal. The upgraded in-game UI will encompass additions like a pause screen, dynamic background animations, and informative buttons and tiles that provide real-time information about the game's status. The second aspect of this feature will focus on adding new audio elements, including ambient background sounds, button click sounds, and interactive audio cues.

## SubFeature
This feature can be broken into the following subfeatures:

### Map improvements - 1 member
This feature includes improving the existing map structure, reducing the number of lanes, making sure the mobs and towers fit the lanes and adding new map specific background animations.

### Pause menu and text style- 1 member
This feature will include implementing a pause screen and finalising the text style for the entire game.

### Sounds - 1 member
This feature will implement new sounds for user-game interactions and map specific ambient sounds.

### UI Elements - 2 members
This feature will create a new slider that reflects the current state of the game, new interactive buttons that allow users to skip to the next wave, warning indicators for incoming mobs and mob bosses and a tile to reflect the number of remaining mobs for the current level.

# **Dependencies**

- UI Elements team will need to collaborate with mobs team to implement the next wave button and current mobs button.
- Map improvement team will need to collaborate with team implementing the drag and drop feature to tile highlighting for the map.

# **Milestones**

- [x] Design and planning of Map improvements (Sep. 18)
- [x] Design and planning of Pause menu (Sep. 18)
- [x] Finalising sounds for the game (Sep. 18)
- [x] Design and planning of UI Elements (Sep 18)

****
- [x] Write code and JUnit tests for Map improvement feature (Sep. 24)
- [x] Write code and JUnit tests for Pause menu feature (Sep. 24)
- [x] Write code and JUnit tests for added new UI elements (Sep. 24)

****
- [x] Testing, Debugging, Integration - Map improvements (Sep. 27)
- [x] Testing, Debugging, Integration - Pause menu feature (Sep. 27)
- [x] Testing, Debugging, Integration - Sounds (Sep. 27)
- [x] Testing, Debugging, Integration - added UI Elements (Sep, 27)

****
- [x] Documentation written - Map improvements (Sep. 30)
- [x] Documentation written - Pause menu sub feature (Sep. 30)
- [ ] Documentation written - added sounds (Sep. 30)
- [x] Documentation written - new UI Elements (Sep. 30)

****
**Completion Deadline:** October 1st

# **Extras (optional)**
- [ ] Possible implementation of new maps if new planets are added to the game.
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Ahmad (@The-AhmadAA) (Ahmad Abu-Aysha)
- Alasdair (@AlasdairS4698737) (Alasdair Sinclair)
- Mohamad (@Mohamad11Dab) (Mohamad Dabboussi)
- Praneet (@praneetdhoolia) (Praneet)
- Shivam (@shiv-0831) (Shivam Garg)

**Comment by The-AhmadAA** [comment]
fixed a typo

**Comment by The-AhmadAA** [comment]
Added optional task - some possibility of new planets being added to the game, so may require some new maps/backgrounds

**Comment by The-AhmadAA** [comment]
Sound documentation may need to be rolled into other features as applicable - see #175
