### ISSUE TITLE
[Team 1] New General Mob Designs/Animations

### ISSUE THREAD

**Issue by MiniSoda17** [UQcsse3200/2023-studio-3#171]
# **Description**
**Task:** [New General Mob Designs/Animations](#171).
**Feature:** [Team-1 Mobs Enhancement](#167)

For this sprint, I will have two main focuses. One, choosing and implementing all the design and animations for general mobs. This will include having similarly themed mobs to their respective planets or projectiles they are shooting. My next focus will be implementing collision effect animations to Mobs. So whenever they are hit but a slow or stun effect, there will be a visible indicator within the mobs that they are being hit by those effects. 
 
## **Example (optional)**
- **Unique Design & Animations**: Each mob will be able to be uniquely identified and you can tell which level/planet they belong to.
- **Collision Effect Indicator**: Once a mob is hit by a slow effect, it will slightly adjust the mob to be a blue color to indicate that it is being slowed. Or when it is being hit by a burn effect, it will become red. 
# **Dependencies**

- [x] New general mobs need to be created so I can implement design and animations on them()
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Finalise all mob themes for the three planets (Sep. 17)
- [x] Add all necessary images and atlases to in-game assets  (Sep. 20)
- [x] Implement design & animations in general mobs for Lava Planet (Sep. 23)
- [x] Implement design & animations in general mobs for Ice Planet (Sep. 25)
- [x] Implement design & animations in general mobs for Mud Planet (Sep. 27)
- [x] Implement reworked mob ranged task (Sep. 27)
- [x] Implement reworked mob melee task (Sep. 29)
- [x] Implement all Junit Testing (Oct. 1)
 
**Completion Deadline:** Oct. 2
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Isaac (@MiniSoda17 ) (Isaac Arli)
