### ISSUE TITLE
[Team-1] Creation of Ice Mob Boss

### ISSUE THREAD

**Issue by cindyle1** [UQcsse3200/2023-studio-3#172]
# Description
Task: [Mob king animations + variation](#172)
Feature: [Mob Enhancements](#167)

This task ticket will consist of adding animations for new mob kings as well as creating a mob king that is able to spawn general mobs. This will allow for differentiation between planets/levels. Another feature is sound effects and health bar of the mob king. 

**Ice Mob Boss**
Spawn/hatch general mobs that attack and shoot towers. 

# **Dependencies**
- [x] Finalisation of image packs
- [x] Finalisation of types of planets

# **Milestones**
List of steps that need to be completed for this task:
- [x] Decide on which planet the mob kings will be on (Sep. 18)
- [x] Finalise mob boss images (Sep. 18)
- [x] Create ice mob boss(Sep. 29)
- [x] Add animations for ice boss (Sep. 29)
- [x] Add sound effects for specific ice boss (Sep. 29)
- [x] Add JUnit tests (Oct. 1)

**Completion Deadline:** Oct. 1

# **Documentation**
 - [Mob King animation controller](https://github.com/UQcsse3200/2023-studio-3/wiki/Mob-Boss-Animation-Controller)
 - [Mob King Factory](https://github.com/UQcsse3200/2023-studio-3/wiki/Boss-King-Factory)

# **Member**
- Wing Yan Lee (@cindyle1) (Cindy)
