### ISSUE TITLE
[Team 1] Mob Mechanics Variations

### ISSUE THREAD

**Issue by freshc0w** [UQcsse3200/2023-studio-3#173]
# **Description**
**Task:** [Mob Mechanics Variations](#173).
**Feature:** [Mobs Enhancement](#167)

For this task, I will be implementing various general mob mechanics to promote diverse and interactive gameplay. This includes, splitting/cloning of multiple 'moblings' at set positions, mobs that can dodge or teleport projectiles with a set cooldown, mobs that phase through projectiles (or go underground) and a mob that deflects incoming projectiles. If time allows, possible extensions could include drop-down mobs that steals/targets enemy towers, hypnotised mobs that target other mobs and mobs that empowers other mobs within a certain radius. For the sake of simplicity, these mechanics won't be dynamic or flexible enough to be individual components, but rather be it's own categorized mobs.

Sept 29. EDIT: Individualized these mechanics into individual components and tasks, making it easier to implement into different types of mobs.

# **Dependencies**
- [x] Graphic and animation effects with different types of mobs need to be discussed and created. (#171)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Splitting/Cloning of moblings (Sept. 19)
- [x] Junit testing of splitting/cloning mobs (Sept. 21)
- [x] Implement deflecting mechanics (Sept. 22)
- [x] Junit testing of deflection mechanics (Sept 24.)
- [x] Dodging/Teleporting mobs (Sept. 26)
- [x] Junit testing of dodging/teleporting mobs (Sept. 27)
- [x] Start documentations (Sept 29.)
- [x] Enforce and finalist code styling and refactoring (Sept 30.)
- [x] Finalise documentation (Sept 31.)
 
**Completion Deadline:** Sept 31.
 
# **Documentation**
- [Wiki DeflectingComponent](https://github.com/UQcsse3200/2023-studio-3/wiki/Deflecting-Component)
- [Wiki SplitMoblings](https://github.com/UQcsse3200/2023-studio-3/wiki/Split-Moblings)
- [Wiki DodgingComponent](https://github.com/UQcsse3200/2023-studio-3/wiki/Dodging-Component)
- [JavaDoc DeflectingComponent](https://uqcsse3200.github.io/2023-studio-3/com/csse3200/game/components/npc/DeflectingComponent.html)
- [JavaDoc SplitMoblings](https://uqcsse3200.github.io/2023-studio-3/com/csse3200/game/components/npc/SplitMoblings.html)
- [JavaDoc DodgingComponent](https://uqcsse3200.github.io/2023-studio-3/com/csse3200/game/components/npc/DodgingComponent.html)
 
# **Member**
- Chia-Chuan Tsou (@freshc0w)
