### ISSUE TITLE
[Team 2] Pause menu

### ISSUE THREAD

**Issue by AlasdairS4698737** [UQcsse3200/2023-studio-3#174]
# **Description**
**Task:** [Team 2] Pause menu.
**Feature:** [Team 2] In-game UI and sounds feature ticket. (#170)

This task's goal is to implement a pause button to allow players to pause the game during a level. The pause menu shall have the following 4 buttons: Continue, Back to planet select, Settings, and Back to main menu.

# **Dependencies**
- [ ] (#170)
- [ ] (#175)
- [ ] Wave pausing functionality in SpawnWaveTask class.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement pause button interaction (Sep. 20)
- [x] Implement game pausing functionality (Sep. 22)
- [x] Implement pause menu buttons (Sep. 26)
- [x] Double check to ensure javadoc comments are present and junit tests are implemented (and that the code passes them) (Sep. 30)
 
**Completion Deadline:** Oct. 2

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Alasdair (@AlasdairS4698737) (Alasdair Sinclair)
