### ISSUE TITLE
Team-2 In-Game Sounds and Background Music

### ISSUE THREAD

**Issue by The-AhmadAA** [UQcsse3200/2023-studio-3#175]
# **Description**
**Task:** [Game UI Sounds and In-Game music/ambient sound](#3).
**Feature:** [Team-2 In-Game UI and Sound](#170)

This task ticket covers the implementation of In-Game UI sound effects, music and ambient sound. There will be close collaboration with Team 3 (Pre- and Post-Game UI) for standardisation of sound effects throughout the UI, along with balancing of sound levels, and triggering mechanisms. 
 
## **Examples of Sound effects to be implemented**

* Button press and hover
* ~~Build menu effects~~
* ~~Placement of towers~~
* Spawning of Engineers
* Menu pop up and closing
* ~~Pause menu sounds~~
* ~~Ambient game sounds~~
* ~~Background music - standard (changes with level)~~
* ~~Background music - Boss presence~~
* ~~Boss announcement sounds~~
* If story elements are introduced, story sound effects
* Win sounds
* ~~Lose sounds~~
* Invalid action sounds
* ~~Wave start sounds~~

There may be more sounds that are not covered here, nevertheless this task ticket intends to cover them.

# **Dependencies**
This ticket is anticipated to interact closely with many features of the game, and as such, has multiple dependencies.

- [x] In-Game Build Menu
- [x] In-Game UI elements #182 
- [x] In-Game Tower pop-up menus #188
- [ ] Win state
- [x] In-Game Pause Menu #174 
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] Incorporate background music for all implemented levels (18 Sep)
- [x] Incorporate ambient sounds for all implemented levels (19 Sep)
- [ ] Incorporate various UI sound elements into in-game UI (22 Sep)
- ~~[ ] Implement enemy and engineer spawning related sounds (22 Sep)~~ This is being implemented in #189 (Mobs) and #184 (Engineers) 
- [ ] Documentation completed  (22 Sep)
- [ ] Testing completed (22 Sep)
 
**Completion Deadline:** Oct 1.
 
# **Documentation**
- [Main description of feature](../wiki/UI-Sound-Elements)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Ahmad (The-AhmadAA) (Ahmad Abu-Aysha)

**Comment by The-AhmadAA** [comment]
**This ticket has uncompleted subtasks which will be carried over into future improvements, namely:**
* Additional UI sounds in-game
* Ensuring pre- and post- game UI sounds are consistent
* tweening of sounds between screens
* Documentation and testing is very disjointed due to sounds being part of many different classes and features, and may need to be rolled into the testing for each of them. In the interim, sound testing was carried out manually during development, by ensuring that sounds correctly loaded and played when they were supposed to.
