### ISSUE TITLE
[Team 1] Mob Boss Base Functionality and New Mob Boss

### ISSUE THREAD

**Issue by JSLLW** [UQcsse3200/2023-studio-3#177]
# **Description**
**Task:** [Mob Boss Base Functionality and New Mob Boss](https://github.com/UQcsse3200/2023-studio-3/issues/177)
**Feature:** [Mobs Enhancement Feature](https://github.com/UQcsse3200/2023-studio-3/issues/167)

Clean up code for BossKingFactory and creating a mob boss that has a high health value and can wipe out a tower or engineer in one hit. The new mob boss doesn't have any projectile attacks but it's melee attack should be powerful enough to destroy a tower in one hit or kill an engineer in one hit. It may also have the ability to attack projectiles so it doesn't take damage, but this should only be possible for either a specific type of projectile or having a cool down period.

# **Dependencies**
- [ ] [Animations for Mob Bosses](https://github.com/UQcsse3200/2023-studio-3/issues/172)
 
# **Milestones**
- [ ] Clean up code for BossKingFactory for the mob bosses. (Sep. 23)
- [ ] Enlarge the Mob Boss to take up more lanes. (Sep. 24)
- [ ] Create new mob boss. (Sep. 27)
- [ ] Create attack for mob boss. (Sep. 28)
- [ ] Implement projectile attack. (Sep. 30)
- [ ] Test mob boss. (Oct. 1)
- [ ] Updating and adding documentation for mob bosses. (Oct. 1)
 
**Completion Deadline:** Oct. 1
 
# **Documentation**
- [Boss features](../wiki/Entities)
- [Animations](../wiki/Animations)
- [Boss King Factory](../wiki/Boss-King-Factory)
 
# **Member**
- Josephine Wong (@JSLLW ) (s4528565@student.uq.edu.au)
