### ISSUE TITLE
[Team-3] Enhance Main Menu And Settings Screen

### ISSUE THREAD

**Issue by aadityayadav17** [UQcsse3200/2023-studio-3#178]
# **Description**
**Task:** UI & Animation Enhancements
**Feature:** [[Team-3] UI Feature Ticket (Sprint-3)](#164)

The tasks in this ticket aim at improving the game's UI. These include introducing a more dynamic background for the Main Menu & Settings Screen, and visually enhancing them.

# **Dependencies**
- Collaborate with the towers team for turret screen selection and visuals (**update with reference**)
 
# **Milestones**
- [x] Dynamic Background for Main Menu Screen (Sept. 20)
- [x] Dynamic Background for Settings Screen (Sept. 23)
- [x] Make minor visual tweaks to the Turret Screen (Sept. 29)
 
**Completion Deadline:** Sept. 30

# **Documentation**
- [UI](../wiki/UI)
- [Animations](../wiki/Animations)
- [Settings](../wiki/Settings)
- [New Levels Task](../wiki/New-Levels-Task)
 
# **Member**
- Aaditya (@aadityayadav17) (Aaditya Yadav)
