### ISSUE TITLE
[Team 5] UI Implementation

### ISSUE THREAD

**Issue by nawal-0** [UQcsse3200/2023-studio-3#18]
# **Description**
**Task:** UI Implementation (#18).
**Feature:** Economy (#15)

Implementing the UI of the economy system on the game screen. The currency should display when dropped and disappear after the player ‘takes’/clicks on it. This task also includes adding a section to the menu which shows the player how much of the currency they currently own. Also involves making sure it updates when players pick up more/use up ‘scraps’. 

# **Dependencies**
- [x] UI Design (#16)
- [x] Abstraction of Currency Class (#19)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Plan and design the user interface. Collaborate with the Interface Team as needed regarding placement of the currency on the menus, etc. (Aug. 19)
- [x] Implement interface (Aug. 26)
- [x] Testing and Documentation (Aug. 27)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Nawal (@nawal-0) (Nawal)
- Sonja (@SonjaMcNeilly) (Sonja)
