### ISSUE TITLE
[Team-3] Story screen implementation

### ISSUE THREAD

**Issue by Octagunn** [UQcsse3200/2023-studio-3#180]
# **Description**
**Task:** [implementation of story screen and elements and a skip button](#3).
**Feature:** [[Team-3] UI Feature Ticket](#164 )

during this sprint the aim of this task is to improve and reimagine the story screen before the game starts that gives background to the events in the story . the idea is to add all new comic style artwork along with other elements that'll make the story screen dynamic and engaging along with the task of adding a skip button that'll allow players to skip the screen 
 

# **Dependencies**

-  Design committee to advise on the art style and story beats for the game screen  

# **Milestones**
List of steps that need to be completed for this task.
- [x] create the artwork for the cutscenes (Sept. 21)
- [x] create and polish other elements for the scenes (Sept. 24)
- [x] create and add skip button (Sept. 27)
- [x] polish the overall scenes and add more if there is time (Sept. 29)
 
**Completion Deadline:** Sept. 30

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Rakshit Nandal (@Octagunn ) (Rakshit)
