### ISSUE TITLE
[Team 7 Towers] Enhancement on towers, new Towers and bomb ship

### ISSUE THREAD

**Issue by karthikeya-v** [UQcsse3200/2023-studio-3#181]
## **Description**
This sprint the goal of team 7 is to improve on the already existing tower components, create new towers for unused components of projectiles (any unused projectiles) also to implement new features like a bomb dropping ship and adapting to the new map teams changes.

## Sub-Feature / Component (optional)
Adapting to map teams lane changes position adjustment.

## Create new towers - 2 members
Creating new towers and using the unused projectiles from last sprint for the attack component of these towers.

## Adapting to lane changes - 1 member
Adapting to the lane changes introduced by the new map team when cleaning (feature ticket #170).

## Adding the bomb ship feature - 2 members
Creating a bomb ship to come and attack mobs in between the game and drop a bomb to deal damage (feature needs to be discussed with the team 2 and design committee)?? A new task ticket will be produced with updated task features.

## Cleaning up the code - every member
Cleaning up their tasks code after the new changes to adapt to the already existing team 2 code.

# **Milestones**
List sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1  - New towers (number based on unused projectiles) (Aug. 20) #193 
    - [x] Design new towers
    - [x] Choose artwork
    - [x] Implement new towers
    - [x] Implement functanality
    - [x] Create documentation 
- [ ] Goal 2 - Adapting to lane changes made by the maps team and positioning (Aug. 2)
    - [ ] Updating the map spawning positions of the towers based on new map changes
    - [ ] Cleaning up the code to remove collisions
- [ ] Goal 3 - Creating  a bomb ship to deal damage to mobs (Aug. 26) #210 
    - [x] Talk to team 2 (their idea) and design committee to understand the feature in-depth
    - [x] Choose artwork
    - [ ] Implement the functionality
    - [ ] Testing
    - [x] Create documentation
- [ ] Goal 4 - Cleaning up the work done (Aug. 28)
    - [ ] Just basic cleanup of the code to make sure everything works.
    - [x] Fixing code smells

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Will add new towers other than the needed ones just for different maps based on the maps to create a sense of color scheme and towers being different for different planets (will try to match the color scheme with the attack we choose for the towers)

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- karthikeya v @karthikeya-v
- Thivan @ThivanW 
- Vishal  @Vishal-jodd 
- Ken @lenhatminh451 
- Deven @dbhasin4123
