### ISSUE TITLE
[Team 2] UI Elements

### ISSUE THREAD

**Issue by praneetdhoolia** [UQcsse3200/2023-studio-3#182]
# **Description**
**Task:** [UI Elements](182)
**Feature:** [In-game UI and sounds feature ticket](170)

This task focuses on adding various new elements to the game's user interface, such as buttons, displays and popups. The goal is to make the current game significantly more interactive and enjoyable for the user. The UI elements will play a key role in the future gameplay and assist the player throughout the game session.
 
## **Features**
- **Pause Button:** There will be a button to pause the game at any time. It will trigger an event for the pause menu.
- **Game State Slider**: A left to right slider will indicate the progress that has been made in the current wave so far.
- **Early Wave Button:** The player will be prompted to skip to the next wave during the cooldown after every wave.
- **Remaining Mobs Tile:** The remaining number of mobs in a particular wave will be displayed in a numerical tile.
- **Incoming Mob Warning:** A warning detailing severity of incoming mobs will be displayed in their specific lane.
- **Incoming Wave Timer:** A timer (_minute : second_ format) will display the remaining time till the coming wave.
- **Wave Number Tile:** A label displaying the current wave number.

### **Dynamic Functionality:**
The remaining mobs tile will be replaced by a timer for the incoming wave upon completion of a wave. A button to skip to the next wave will also be displayed along with the timer, allowing the player to start the wave early.

### **Stretch Goals**
- **Enemy Entry Alert:** Some effects and an alert will be displayed when a mob enters the base.
- **Boss Screen Flash:** The screen may lightly flash red when a boss spawns to indicate severity.
- **Next Wave Enemy List:** A popup to display the mobs and their types in the incoming wave.
- **Wave Win Message:** A victory message may be displayed with effects after winning a wave.

# **Dependencies**
- [x] #78
- [x] #89
- [x] #90
- [x] #167
- [x] #185
- [ ] #186
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Finalization of new UI elements placement. (Sep. 18)
- [x] Programming and debugging UI elements. (Sep. 24)
- [x] Testing and Integration of new UI into main. (Sep. 27)
- [x] Adding UI elements documentation to wiki. (Aug. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- Work in progress
 
# **Member**
- Praneet (@praneetdhoolia) (Praneet)
- Shivam (@shiv-0831) (Shivam Garg)

**Comment by praneetdhoolia** [comment]
Added additional features, constraints and other relevant details.

**Comment by praneetdhoolia** [comment]
Added new dependencies.
