### ISSUE TITLE
[Team 4] Levels & Mob Waves

### ISSUE THREAD

**Issue by meganroxburgh** [UQcsse3200/2023-studio-3#183]
# **Description**
This feature will work on incorporating the existing waves of the mobs spawning. We will work on allowing an initial time for players to set up their towers, then begin the first wave. Once a wave has been completed, there will be a sort grace period before the next wave starts. We will also include some visual cues for the player to see how long until the next wave. 

## SubFeature/component
- Managing the number of mobs and types of mobs per wave
- Managing the frequency of the waves based on time and when waves have been completed

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Allowing the initial time when the level starts for players to place towers before wave 1 starts (Sept. 19)
- [x] Adding in the number of mobs/types of mobs per each wave and also dependent on which level (Sept. 22)
- [ ] Countdown to waves, which wave they are up to (in the background)  (Sept. 24)
- [x] Adding in multiple waves being called when one wave ends, variable time when the last mob of the previous wave is killed (Sept. 26)
- [x] Add in sound effects when a new wave is about to start (Sept. 28)
- [x] Implement difficulty which scales all the levels to either be normal or hardcore (more mobs, more waves) (user selects at the start of level 1)  (Sept. 30)
- [x] Testing plan (Sept. 30)
- [x] Wiki Documentation, UML and Sequence diagrams (Sept. 31)

**Completion Deadline:** Oct. 3

# **Extras**
- [ ] Have the option to skip forward through the initial waiting period before the first wave if the player is ready (being completed by UI team)

# **Documentation**

# **Members**
- Megan Roxburgh (@meganroxburgh )
- Blair Cannon (@BlairCannon97 )
- Sam Sullivan (@samsully )
- Miles Bojorge (@bojyyy )
- Max Taylor (@max9753 )
