### ISSUE TITLE
[Team 5] Engineer Controller

### ISSUE THREAD

**Issue by ryandmcneilly** [UQcsse3200/2023-studio-3#184]
# **Description**
**Task:** Engineer Controller (#184).
**Feature:** (Enhancing existing UI and Engineer Controller #195).

The current state of the engineers, the engineers spawn after a certain number of conditions are met. A controller can be added to the engineer such that if an engineer is clicked, the user can control the engineer in an RTS fashion. This means when an engineer is in 'control' the engineer can choose to move, repair and shoot with the engineer.

 
## **Example**
- **Engineer Outline**: After clicking on an engineer, an outline will be drown around the current engineer showing it has been selected.
- **Engineer repair**: An engineer can repair a turret by right clicking the turret. The engineer will go to the turret and start 'repairing'

# **Dependencies**
This task assumes interaction with the grid is implemented.
 
# **Milestones**
List of steps that need to be completed for this task.
#### Goal 1 (Sep 23): Planning and Scaffolding 
- [x] Learn the current Engineer implementation
- [x] Understand which services and interfaces will be needed
- [x] Planning animation design.

#### Goal 2 (Sep 27) Code Implementation and Test Design (JUnit)
- [x] Design and implement a testing suite
- [x] Implement engineer outline
- [x] Implement engineer repair

#### Goal 3 (Sep 30) Testing and Debugging; Integration
- [x] Debug faulty code
- [x] Test edge cases with movement

#### Goal 4 (Oct 2) Documentation
- [x] Document code and testing suite
 
**Completion Deadline:** Oct. 2
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Ryan (@ryandmcneilly ) (Ryan McNeilly)
- Nawal (@nawal-0) (Nawal)
