### ISSUE TITLE
[Team 4] Mob selection for levels

### ISSUE THREAD

**Issue by bojyyy** [UQcsse3200/2023-studio-3#185]
# **Description**
**Task:** Mob selection for levels (#185).
**Feature:** Levels & Mob Waves (#183)

This task involves determining appropriate mobs for each level. For each wave, there will be a selection of mobs which will spawn in a set order. A delay between each mob spawning will also be set.
 
## **Example**
- **Level**: For the first level, there might be 12 Xeno grunts that spawn, 3 in the first wave, 4 in the second etc.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] General Mobs (#4)
- [ ] Boss Mobs (#10)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial planning of classes and unit tests (Sep. 19)
- [x] Functionality implemented (Sep. 25)
- [x] Unit testing completed (Sep. 27)
- [x] Documentation completed (Sep. 30)
- [x] Integrated with main (Oct. 2)
 
**Completion Deadline:** Oct. 3

# **Documentation**
 
# **Member**
- Miles Bojorge (@bojyyy ) (Miles Bojorge)
