### ISSUE TITLE
[Team 4] Wave Manager

### ISSUE THREAD

**Issue by meganroxburgh** [UQcsse3200/2023-studio-3#186]
# **Description**
**Task:** [Wave Manager](#186)
**Feature:** [Levels & Mob Waves](#183)

This feature will organise the waves that will be created during a particular level, based on the mobs selected (#185). It will set up a Wave Manager class and when all mobs from a wave have been killed, some time will elapse, and then another wave will begin.

# **Dependencies**
- [ ] Mob selection for levels (#185)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Have one way successfully beginning (Sept. 20)
- [ ] Have multiple waves occurring with some set time period between them (Sept.20)
- [ ] Set an initial delay so the wave begins after some time when the game has spawned. (Sept. 22)
- [ ] Incorporate mob selection (Sept. 26)
- [ ] Testing (Sept. 27)
- [ ] Level completion when last wave defeated (Sept. 28)
- [ ] Wiki documentation (Sept. 30)
 
**Completion Deadline:** Sept. 30
 
# **Documentation**
 
# **Member**
- Name (Megan Roxburgh) @meganroxburgh
