### ISSUE TITLE
[Team 5] Turret Selection Development

### ISSUE THREAD

**Issue by SonjaMcNeilly** [UQcsse3200/2023-studio-3#187]
# **Description**
**Task:** [Turret Selection Development].
**Feature:** Enhancing existing UI and Engineer Controller (#195)

This task is to update the UI of the turret selection, and linking the turrets that are selected in the turret select screen to the main game screen. The UI of the turret selection screen will be updated to a grid style, when hovering over a turret in turret selection screen it will loop an animation, and when selected the box will have an indication that it has been selected (where it has been greyed out, or brackets appear around it), and a description will fade in when hovering for more than a second.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Drag and drop implementation for contents of selectedTurrets (#207)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Put individual towers into a grid (Sept. 26)
- [x] #207
- [x] Hover animation and description done (Sept. 30)
- [x] Indication of clicked displayed (Oct. 2)
 
**Completion Deadline:** Oct. 2
 
# **Documentation**
- [Turret Select Screen](https://github.com/UQcsse3200/2023-studio-3/wiki/Turret-Selection-Screen)
 
# **Member**
- Sonja McNeilly (SonjaMcNeilly) (Sonja McNeilly)
