### ISSUE TITLE
[Team 5] Turret Upgrades UI

### ISSUE THREAD

**Issue by Hasakev** [UQcsse3200/2023-studio-3#188]
# **Description**
**Task:** Turret Upgrades
**Feature:** Enhancing existing UI and Engineer Controller (#195)

This task ticket focuses on the implementation of the turret upgrade such that when a turret is clicked, a UI menu appears displaying the health and damage (if applicable) of the turret.
 
## **Example**
- Upgrade UI: When clicking a turret, a pop-up appears that displays turret information and upgrade/repair options.

# **Dependencies**
- Dependency 1 (#86 ), need to contact Team 2 for how backend works.
 
# **Milestones**
List of steps that need to be completed for this task.
#### Goal 1 (Sep 24): Planning and Scaffolding 
- [x] Plan out design of UI
- [x] Design and plan the implementation of the turret upgrade UI

#### Goal 2 (Sep 28) Code Implementation and Test Design (JUnit)
- [x] Implement turret upgrade UI
- [x] Write tests for upgrade (ensure use of mocking)

#### Goal 3 (Sep 30) Testing and Debugging; Integration
- [x] Communicate with other teams for integration
- [ ] Test screens with other features from other teams for bugs and issues

#### Goal 4 (Oct 3) Documentation
- [ ] Document the implementation details of the turret upgrade UI
- [ ] Update relevant documentation to reflect the changes made.
 
**Completion Deadline:** Oct 3rd
 
# **Documentation**
TBA
 
# **Member**
- Kevin (@Hasakev) Kevin Luo
- Jackie (@FattyHope) Jackie
