### ISSUE TITLE
[Team 4] Wave sounds

### ISSUE THREAD

**Issue by BlairCannon97** [UQcsse3200/2023-studio-3#189]
# **Description**
**Task:** [Wave sounds](#3).
**Feature:** [Waves](#2)

Implement a sound component into waves and wave transitions. These components serve as a quality of life feature, mainly as an audio cue to the player to suggest a wave has started/ended or a special event has occured. The sounds will be consistent with the existing sounds and theme, and will exist to infulence the players thoughts and emotions while they are playing.
 
## **Example**
When a wave begins, a short tune/sound effect will play to suggest an event has begun. This sound will ideally exist to build up anticipation for the upcoming wave, and convince the player that the wave will be dangerous.
Once a wave ends, a short tune/sound effect will play to suggest the wave is over. This tune should convey feelings of relief, and exist as a congratulations to the player for surviving a wave.

# **Dependencies**

- [x] Waves will need an initiation point in order to trigger a sound 
- [x] Waves will need to conclude in order for a conclusion sound to occur 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Source sound effects available online (Sep. 23)
- [x] Implement the effects such that they trigger with the waves (Sep. 25)

# **Extras**
- [ ] Run any additional battle music or boss music which may be suitable by design committee
 
**Completion Deadline:** Sep. 26
 
# **Member**
- Name (BlairCannon97)
