### ISSUE TITLE
[Team 5] Design and Abstraction of Economy

### ISSUE THREAD

**Issue by ryandmcneilly** [UQcsse3200/2023-studio-3#19]
# **Description**
**Task:** Design and Abstraction of Economy (#19).
**Feature:** Economy (#15).

Designing the economy system within the game. This entails dealing with the abstraction of currency, making it easier to be able to in implement more than one currency down the track. Balancing the economy also falls under this task, making decisions on how much individual turrets should cost and how much income the user can generate.  

 
## **Example (optional)**
- **Scrap mine**: This will be one of the main forms of income for the user and will need to interact with the currency.
- **Scrap on mob death**: When a mob dies it will drop scrap, increasing the user's total scrap.

# **Dependencies**
This task does not rely on other tasks.
 
# **Milestones**
List of steps that need to be completed for this task.
#### Goal 1 (Aug 20): Planning and Scaffolding 
- [x] Design of Currency abstract class
- [x] Design on interaction with Currency class
- [x] Planning required methods needed for the class

#### Goal 2 (Aug 23) Code Implementation and Test Design (JUnit)
- [x] Design and implement a testing suite
- [x] Implement interaction with currency functionality

#### Goal 3 (Aug 26) Testing and Debugging; Integration
- [x] Debug faulty code
- [x] Implement interaction with currency functionality

#### Goal 4 (Aug 29) Documentation
- [x] Document code and testing suite
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Ryan (@ryandmcneilly ) (Ryan McNeilly)
