### ISSUE TITLE
PROJECTILE TASK

### ISSUE THREAD

**Issue by ElanagaiArivuchelvan** [UQcsse3200/2023-studio-3#190]
# **Description**
**Task:** [Improving the projectiles effect](#3).
**Feature:** [Projectiles](#2)

Projectile effects in this game will include a variety of visual, aural, and practical components that enhance the entire gaming experience. These effects seek to replicate the chaos and ferocity of combat while giving players constructive criticism and boosting immersion in the game.

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Analyse the projectile class created by the previous team
- [ ] Understand the issue mentioned by them and the feature where improvement needs to be made
- [ ] Implement a seamless projectile to various effects like burn and freeze
- [ ] Test and check if the projectile smoothly integrates to the game environment
 
**Completion Deadline:**  October 2

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Rahul Sagar Pabba (@rahulsagar500)
-  Vansh Mittal (@V4N5HM)
