### ISSUE TITLE
[Team 7] New Towers

### ISSUE THREAD

**Issue by ThivanW** [UQcsse3200/2023-studio-3#193]
# **Description**
**Task:** [New Towers](#3).
**Feature:** [enhancement on towers, new Towers and bomb ship](#181)
 
Each tower shoots out its own unique projectile. Currently there are numerous projectiles that haven't been used  by any of the current towers. These towers should shoot out their associated projectile in the same fashion that the rest of the implemented towers do.

# **Dependencies**
- [ ] The towers need to implement the previously made projectiles (#7)
- [ ] The towers need to match the behaviour of the other towers in order to feel associated but not the same (#6)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] design new towers (Sep. 27)
- [ ] choose art work (Sep. 27)
- [ ] implement new towers (Sep. 29)
- [ ] implement functionality (Sep. 30)
- [ ] create documentation (Oct. 3)

**Completion Deadline:** Oct. 3
 
# **Documentation**
- to be added
 
# **Member**
- Thivan (@ThivanW) (Thivan Wijesooriya)
- Sai (@karthikeya-v) (karthik)
