### ISSUE TITLE
[Team 4] Difficulty

### ISSUE THREAD

**Issue by samsully** [UQcsse3200/2023-studio-3#194]
# **Description**
**Task:** [[Team 4] Difficulty]
**Feature:** [[Team 4] difficulty and waves](#183)

The feature will alter each wave based on difficulty, and progression through the game. The further into the game, the more abilities, health and damage the mobs will do. The user may also set the difficulty. This will not implement the user interface to choose, only account for the backend of setting the difficulty. This will be built off the abstract Wave entity which is responsible for storing and responding to a wave task. 

# **Dependencies**
- [x] Wave manager (#186)
- [x] Wave class
This cannot be implemented until the wave base class has been built as this builds upon the structure. It also requires to wave manager, as the alterations of the mobs will depend on which update of wave manager is occuring.

# **Milestones**
List of steps that need to be completed for this task. Note that these depend on the progression of the dependencies. 
- [x] Determine how waves will increment health, strength etc (Sep. 27)
- [x] Implement the incrementation with the wave class (Oct. 29)
- [x] Apply the increment to occur during generation of wave mobs (Oct. 1)
- [x] Create a set difficulty which is a factor to apply to the incrementation (based on user selection of difficulty) (Oct. 2)
 
**Completion Deadline:** Oct 2
 
# **Member**
- Samantha Sullivan (@samsully)
