### ISSUE TITLE
[Team 5] Enhancing existing UI and Engineer Controller

### ISSUE THREAD

**Issue by ryandmcneilly** [UQcsse3200/2023-studio-3#195]
# **Description**
**Feature:** Enhancing existing UI and Engineer Controller (#195)

This task deals with enhancing existing UI components including the current Turret Selection (more visually appealing), and current Turret placement mechanics. An "Engineer Controller" will also be implemented, where the user can move engineers and repair turrets with engineers. With this functionality, the game will feel more interactive for the user as they have now engineers to move around the map. 

 
## **Example**
- **Engineer Movement**: Engineers will be able to move around the map.
- **Turret Placement**: The player can buy turrets and place them on the map in exchange for currency
- **Turret Selection**: The boss mobs will now be larger, spanning multiple lanes which allows them to be targeted by towers from multiple lanes, adding a new layer of strategy and excitement to the gameplay.

# **Dependencies**
This ticket relies on the completion of all subfeatures (task tickets):
- Turret Upgrades UI (#188)
- Turret Selection Development (#187)
- Engineer Controller (#184)
- Turret Placement (#xx)

# **Milestones**
#### Goal 1 (Sep 19): Planning and Scaffolding 
- [ ] Engineer Controller
- [ ] Turret select screen
- [ ] Turret placement #205 
#### Goal 2 (Sep 30) Code Implementation and Test Design (JUnit)
- [ ] Engineer Controller
- [ ] Turret select screen
- [ ] Turret placement
#### Goal 3 (Oct 2) Testing and Debugging; Integration
- [ ] Engineer Controller
- [ ] Turret select screen
- [ ] Turret placement #205 
#### Goal 4 (Oct 2) Documentation 
- [ ] Engineer Controller
- [ ] Turret select screen
- [x] Turret placement

**Completion Deadline:** Oct 3

# **Documentation**
TBA

# **Members**
Ryan (@ryandmcneilly) (Ryan McNeilly)
Sonja (@SonjaMcNeilly) (Sonja)
Nawal (@nawal-0) (Nawal)
Jackie (@FattyHope) (Jackie) 
Kevin (@Hasakev) (Kevin Luo)

**Comment by The-AhmadAA** [comment]
In-Game build menu has been implemented, see #205 which should be merged into main soon. JUnit tests and Documentation to follow
