### ISSUE TITLE
animation rendering

### ISSUE THREAD

**Issue by ElanagaiArivuchelvan** [UQcsse3200/2023-studio-3#196]
# **Description**
**Task:** [Adding Animation](#3).
**Feature:** [Projectiles](#2)

In the context of projectiles, the animation function is utilised to graphically describe and replicate projectile motion, making it simpler for users to understand their behaviour under various circumstances. It's an important tool. 

# **Dependencies**

no major dependencies as it is basically a render animation

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Understand the class of the projectiles as this is a new feature
- [x] analyse the types of atlas files and their dependencies for animations
- [x] grab all types of files for a suitable fit animation
- [x] Implement the type of animation
- [x] test to see if the game is running and the animation is being applied to the targets
 
**Completion Deadline:** oct 2

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
-   Elanagai Arivuchelvan (@ElanagaiArivuchelvan)
-  Sahajdeep Singh (@sahajdeep31)
-  Jigyasu mittal ( @JigyasuMittal )

**Comment by MiniSoda17** [comment]
Hi there, will you be implementing the different projectiles for different mobs?
