### ISSUE TITLE
Team 4 Waves - User/Java Testsing

### ISSUE THREAD

**Issue by BlairCannon97** [UQcsse3200/2023-studio-3#199]
# **Description**
**Task:** Team 4 Waves - Testsing
**Feature:** Waves and Difficulty

Much of the wave base functionality is nearing completeion, however there are still a number of known bugs and issues causing problems. A suite of tests needs to be written for the classes WaveTask, WaveClass , WaveFactory and LevelWaves, in order to achieve full, reliable functionality. Some user feedback will also be gathered surrounding the current difficulty and enjoyment presented by the game in it's current state. This will offer some insight into things that may need to be balanced better or improved upon in sprint 4, but ultimately condribute to a better final product
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write a Test Suite for the classes WaveTask and WaveClass (Sept. 30)
- [x] Write a Test Suite for the classes LavelWaves and WaveFactory (Oct. 01)
- [x] Gather feedback from individuals outside the project regarding the current balance (Oct. 02)
 
**Completion Deadline:** Oct. 03

 
# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2023-studio-3/issues/183)
 
# **Member**
(@BlairCannon97 )
