### ISSUE TITLE
Tutorial 2 dummy ticket

### ISSUE THREAD

**Issue by The-AhmadAA** [UQcsse3200/2023-studio-3#2]
# **Description**
This a dummy ticket created during the tutorial. For implementing the game map in which all the towers, mobs and environmental effects will occur. The map is an isometric view of the planetary surface, which contains a grid which towers/mobs occupy.
Should allow applying a visual 'skin' which indicates which planet the stage is occurring on.

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.
# **Dependencies**

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Create grid environment (Aug. 20)
- [ ] Implement 'occupation' of grid elements by mobs/towers (Aug. 23)
- [ ] Implement 'skinning' of the environment (Aug. 26)
- [ ] Implement environmental effects? (Aug. 28)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Ahmad (@The-AhmadAA ) (Ahmad Abu-Aysha)

**Comment by Hasakev** [comment]
Woah

**Comment by The-AhmadAA** [comment]
closing to remove - test ticket only
