### ISSUE TITLE
[Team 7] Final Boss Movement And Collision 

### ISSUE THREAD

**Issue by ThivanW** [UQcsse3200/2023-studio-3#20]
# **Description**
**Task:** [Final Boss Movement And Collision](#20).
**Feature:** [Boss Mobs](#10)

The final boss will be the most difficult mob to beat and will be able to move between lanes as it advances towards the ship. When switching lanes the boss will stay on the same column that it was previously on. When hitting a tower the boss will stop moving. In order to keep this balanced the final boss will move slower than a general mob. 

# **Dependencies**
- [ ] The final boss's speed will be less than a general mobs (#xx)
- [x] The final boss will stop moving once it collides with a turret (#6)
- [x] The final boss can switch between lanes (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] The boss moves forward at a constant speed (Aug. 19)
- [x] The boss switches lanes every few seconds (Aug. 24)
- [x] The boss stops moving once it hits a tower (Aug. 28)
 
**Completion Deadline:** Aug. 28
 
# **Member**
- Ken (@lenhatminh451) (Ken Le)
