### ISSUE TITLE
Team 2/Team 5 Collab - In-Game Tower Build Menu

### ISSUE THREAD

**Issue by The-AhmadAA** [UQcsse3200/2023-studio-3#207]
# **Description**
**Task:** [Team 2/Team 5 Collaboration](#195)
**Feature:** [In-Game Tower Select and Build Menu](Part of #187)

This task ticket covers the implementation of In-Game Tower Select and Build Menu, one of the primary interaction mechanisms for players of the game. The build menu allows users to 'buy' the towers that have been selected in the TurretSelectScreen and placed on the map area for defending against alien attacks. This requires interaction with mouse input, currency service and map area functionality.
 
## **Examples of user actions this will cover**

* Selecting a tower from the list of towers
* Checking for tile occupancy
* Checking for sufficient currency
* Spawning of selected towers
* Prevention of tower build if conditions are not met
* Input Handling

# **Dependencies**
This ticket is anticipated to interact closely with TurretSelectScreen, MapService and CurrencyService.

- [x] In-Game UI elements #182
- [x] TurretSelectScreen improvements #187 
- [x] MapService #202 
- [x] CurrencyService
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] Handle Mouse Input
- [x] Integrate Tower selection from select screen
- [x] On-screen tower selection buttons 
- [x] Integrate currency functionality - decrementing
- [x] Spawning of towers
- [x] Condition checking (tile not occupied, sufficient currency)
- [x] Documentation
- [ ] JUnit tests
 
**Completion Deadline:** Oct 2.
 
# **Documentation**
- [Tower Build Menu](../wiki/Tower-Build-Menu)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Ahmad (The-AhmadAA) (Ahmad Abu-Aysha)

**Comment by The-AhmadAA** [comment]
**Additional JUnit tests will be required for this implementation, in addition to the manual testing carried out to ensure functionality**
