### ISSUE TITLE
[Team 7] Boss Damage And Death

### ISSUE THREAD

**Issue by ThivanW** [UQcsse3200/2023-studio-3#21]
# **Description**
**Task:** [Boss Damage And Death](#21).
**Feature:** [Boss Mobs](#10)

The bosses will receive damage from tower projectiles as they advance towards the ship. Upon receiving enough damage the boss will die and despawn. The bosses will be able to withstand more projectiles than a general mob. 

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Bosses will receive damage from tower projectiles (#14)
- [ ] The bosses will have more health than a general mob (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] The bosses each have health points (Aug. 18)
- [ ] The bosses lose health once they are hit by a projectile (Aug. 22)
- [ ] The bosses die once they reach 0 health points (Aug. 25)
 
**Completion Deadline:** Aug. 25
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Sai (@karthikeya-v) (karthik)
