### ISSUE TITLE
[Team 7] Bomb Ship

### ISSUE THREAD

**Issue by lenhatminh451** [UQcsse3200/2023-studio-3#210]
# **Description**
**Task:** [Team 7] Bomb Ship.
**Feature:** [Team 7 Towers] Enhancement on towers, new Towers and bomb ship (#181)

The Bomb Ship is designed to come and attack mobs within the game and drop a bomb to deal damage. This task involves collaboration with team 2 and the design committee to understand the feature in-depth, create a design for it, choose appropriate artwork, and implement its functionality.

# **Dependencies**
- [x] Collaboration with team 2 and the design committee for feature understanding and design.
 
# **Milestones**
List sub-tasks intended to have been done by the end of the sprint:
- [x] Collaboration to understand the concept (Sep. 24)
- [x] Artwork selection (Sep. 26)
- [x] Implement functionalities (Oct. 1)
- [ ] Testing (Oct. 3)
- [x] Documentation (Oct. 3)
 
**Completion Deadline:** Oct 3
 
# **Documentation**
- [Bomb Ship Wiki](https://github.com/UQcsse3200/2023-studio-3/wiki/Bomb-Ship)
 
# **Member**
- Ken (@lenhatminh451) (Ken Le)
- Yelmela (@Vishal-jodd) (Yelmela Vishal)
