### ISSUE TITLE
[Team 7] Boss Attacks

### ISSUE THREAD

**Issue by ThivanW** [UQcsse3200/2023-studio-3#22]
# **Description**
**Task:** [Boss Attacks](#22).
**Feature:** [Boss Mobs](#10)

When the bosses collide with a tower as they move towards the ship, they will stop moving and start making a melee attack. The first boss's also will make ranged attacks as it moves towards the ship. These attacks will damage the towers and destroy them before the bosses move forward again. 
 
# **Dependencies**

- [ ] The bosses attacks will be stronger than the general mobs attacks (#xx)
- [ ] The bosses attacks will decrease the towers health points (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Both bosses have working melee attacks (Aug. 19)
- [x] The first boss has a ranged attack (Aug. 22)
- [ ] The bosses only do their melee attack once they have collided with a tower (Aug. 24)
- [x] The first boss performs their ranged attack every few tiles crossed (Aug. 26)
- [ ] The bosses stop attacking once there is no towers in front of them (Aug. 28)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
