### ISSUE TITLE
[Team 5] Integrate New Towers into Tower Upgrades and Tower Selection Screen

### ISSUE THREAD

**Issue by Hasakev** [UQcsse3200/2023-studio-3#224]
# **Description**
**Task:** [Team 5] Integrate New Turrets into Tower Upgrades and Tower Selection Screen
**Feature:** TBA

> This is a small task

In Sprint 3, Team 7 implemented three new towers,~~(and two WIPs)~~ these include:
(see #213)
- Fireworks Tower
- Pierce Tower
- Ricochet Tower

> ~~- Heal Tower?~~
> ~~- Bomb Ship (#210 ) - need to ask team 7 how this works...[wiki link](https://github.com/UQcsse3200/2023-studio-3/wiki/Bomb-Ship)~~
> Heal tower was scrapped, bomb ship is not a tower and so does not need tower upgrades/selection

Currently these turrets are not included in the tower upgrades and tower selection screen so integration is required.

# **Dependencies**
- Dependencies 1 (#213 ): New towers must be completed
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Ensure towers have associated stats, contact team 7 for clarifications (Oct. 6)
- [x] Integrate upgrade components, integrate into tower selection (Oct. 8)
- [x] Check for bugs (Oct. 8)
- [x] Add new turrets to the turret select screen (Oct. 12)
 
**Completion Deadline:** Oct. 16

# **Documentation**
- [Turret Selection Screen](https://github.com/UQcsse3200/2023-studio-3/wiki/Turret-Selection-Screen)
- [Tower Upgrader Component](https://github.com/UQcsse3200/2023-studio-3/wiki/Tower-Upgrader-Component)
 
# **Member**
- Sonja McNeilly (@SonjaMcNeilly) Sonja
- Kevin Luo (@Hasakev) Kevin
