### ISSUE TITLE
[Team 2] In-Game Tower Build Menu and control improvements

### ISSUE THREAD

**Issue by The-AhmadAA** [UQcsse3200/2023-studio-3#229]
# **Description**
**Task:**  [Team 2] In-Game Tower Build Menu and control improvements

This task aims to complete the implementation of the In-Game Tower build feature that was implemented in sprint 3. The main functionality is complete, but some audio/visual improvements are needed, and some additional control elements may be implemented for better user interaction.
 
## **Example**
__Audio/Visual__ 
The tower build menu buttons are spartan in their appearance and function, and cause some confusion to users. The planned improvements are to implement more visually appealing buttons that convey their function more clearly. The current implementation has buttons that toggle on and off, but this does not relate to the actual build status of the towers, and are point of distraction and confusion. The button appearance will also convey which tower is selected for building, and should toggle off if another tower, or engineer is selected, or once the tower is placed. Finally, invalid moves should be more clearly indicated through better sound (the current sound is too quiet) and visual indications such as the tile highlighting or flashing resource display if the player has insufficient resources.

__Control improvements__
The tower building should only allow a single placement of a tower by default, and the tile highlighting on the map should indicate the validity of the placement, (this will integrate with task #**<insert task>**). Further improvements are planned which should allow users to use keyboard inputs as shortcuts to allow multiple tower placement, or quick select tower types for placement.

# **Dependencies**
This ticket has dependencies on a fix to the engineer/tower control overlap bug and map tile highlighting improvements

- [x] Engineer/Tower control overlap(#226)
- [x] Map tile highlighting improvements (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Replace tower select buttons (09 Oct)
- [x] Fix tower selection indications (09 Oct)
- [x] Single tower placement by default (10 Oct
- [x] Use of a modifier key to allow multiple tower placements (with possible visual indication?) (11 Oct)
- [x] Use of shortcut keys to quick select tower types (11 Oct)
- [x] Modify Currency display to flash if insufficient currency to build (11 Oct)
- [x] Complete remaining testing (13 Oct)
- [x] Complete remaining documentation (15 Oct)
- [x] Clean up all associated code smells (15 Oct)
 
**Completion Deadline:** 15 Oct

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Ahmad (@The-AhmadAA)
