### ISSUE TITLE
Mob Entity Base Class

### ISSUE THREAD

**Issue by samsully** [UQcsse3200/2023-studio-3#23]
# **Description**
The mob entity class will be base class for all mobs. This class will include:
- heath factor
- speed factor
- identity (enemy id)
- base functions (changing associated variables)
- future functions such as images, abilities, dying (unimplemented)
 
The purpose of implementing this is to provide a common base to develop all 'types' of enemies from in the future for simplicity. 

The future functions will require implementation for ALL enemies, however cannot yet completed. They are solely there to indicate essential future implementation of the features.

# **Dependencies**
No dependencies. 

# **Milestones**
- [ ] Design base structure of expected enemy (based off mob expectations) (Aug. 22)
- [ ] Implement Enemy entity instance with factors (Aug. 28)
- [ ] Implement base functions (changing variables)

**Completion Deadline:** Aug. 30

# **Members**
- Samantha Sullivan (@samsully)
