### ISSUE TITLE
[Team ] Projectile Combinations and Animations

### ISSUE THREAD

**Issue by cindyle1** [UQcsse3200/2023-studio-3#230]
# Description
**Task:** [Projectile Combinations and Animations](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

Create different variations of mob balls for specific mobs in each map. Incorporate the projectile effects (split, ricochet, fireworks, stun, burn and slow). Choose appropriate animations for the mobs as well as fixing previous animations such as spinning snowball and spinning burn projectile.
 
## Example 
- **Ice Queen**: Able to shoot projectiles that is able to slow towers
- **Wizard mob**: Able to implement ricochet projectile.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Plan for each combination for all mobs (Oct. 10)
- [ ] Create projectile combinations in ProjectileFactory (Oct. 10)
- [ ] Add asset packs for every mob and mob boss (Oct. 12)
- [ ] Implement Animations for every mob and mob boss (Oct. 14)
- [ ] Fix stacking from projectile effects (Oct. 16)
 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- [ProjectileFactory](https://github.com/UQcsse3200/2023-studio-3/wiki/Projectile-Factory)

# **Member**
