### ISSUE TITLE
[Team 1] Implement singular mob task that controls all mobs

### ISSUE THREAD

**Issue by gregchan550** [UQcsse3200/2023-studio-3#231]
# **Description**
**Task:** [Implement singular mob task that controls all mobs](#3).

This task will be to implement a functional mob task that will control all general mobs. This mob task will be the only task given to general mobs (not including special features such as dodge, etc.). Melee mobs will run in a straight line until a human entity is detected and then attack that entity. Ranged mobs will run in a straight line, stopping to shoot projectiles occasionally. Previous mob wander and mob shoot task had buggy functionality.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement base functionality with simple movement in a straight line (Oct. 7)
- [x] Implement a way to handle all mob animations in one task (Oct. 9)
- [x] Implement melee attack functionality (Oct. 11)
- [x] Implement range attack functionality (Oct. 13)
- [x] Implement death functionality (Oct. 15)
- [x] Implement dodging and deflecting animations
 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (@gregchan550 ) (Gregory)
