### ISSUE TITLE
[Team 1] Fix projectile effects so that burn and slow dont stack

### ISSUE THREAD

**Issue by gregchan550** [UQcsse3200/2023-studio-3#232]
# **Description**
**Task:** [Fix projectile effects so that burn and slow don't stack](#3).

This task will be to create a new component that can be added to any entity where it will manage the effects done by projectiles - burn, slow, stun. The current implementation allows for the burn and slow to be stacked and resets their speeds to the initial speed at impact rather than their actual speed.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement component class to handle effects (Oct 10)
- [x] Handle burn effect (Oct 11)
- [x] Handle slow effect (Oct 12)
- [x] Handle stun effect (Oct 13)
 
**Completion Deadline:** Oct 17
 
# **Member**
- Name (@gregchan550 ) (Gregory)
