### ISSUE TITLE
[Team 1] Implement demon and patrick boss spawning ability

### ISSUE THREAD

**Issue by gregchan550** [UQcsse3200/2023-studio-3#235]
# **Description**
**Task:** [Implement demon and patrick boss spawning ability and fix demon jumping ability](#3).

This task will be to implement a new feature in both Demon and Patrick boss where they spawn an entity during their sequences. The demon boss will spawn a slimey boy entity every time after its fire breath sequence and the patrick boss will spawn 3 wizards after its range attacks. The number of mobs spawned will be adjustable for both.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement method to spawn slimey boys (Oct. 8)
- [x] incorporate method into demon sequence (Oct. 9)
- [x] Implement method to spawn wizards (Oct. 10)
- [x] Rework jump functionality so that demon boss won't slide (Oct 10)
- [x] Incorporate method into patrick sequence (Oct. 11)
 
**Completion Deadline:** Oct. 17

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (@gregchan550 ) (Gregory)
