### ISSUE TITLE
[Team 1] Mob components and task bug fixes

### ISSUE THREAD

**Issue by freshc0w** [UQcsse3200/2023-studio-3#236]
# **Description**
**Task:** [Mob Components/Tasks bug fixes](#3).
**Feature:** 

Main purpose of this task is to address and fix standard bugs seen for different mob components. In particular, it was seen that the `DodgingComponent` sometimes makes the attached entity untargetable from the projectiles due to the dodging nature of the component. Additionally, the animation sometimes does not activate when the dodging component is attached due to task priority issues. It was also observed that the split component occasionally splits the attached entities out of map bounds, making it untargetable for the projectiles as well. These bugs will be addressed this sprint and possible refactoring of game logic might be considered.

# **Milestones**
- [x] Fix dodging component by enhancing collider size of the entity (Oct. 8)
- [x] Fix animation in `DodgeTask` (Oct. 10)
- [x] FIx `SplitMoblings` component by finalising map boundaries (Oct. 12)
- [x] Alter test cases with components, ensuring coherence between animations and mechanics (Oct 15.) 
- [x] Finalise and refactor code (Oct. 17)
- [x] Fixed Unkillable deflect wizard (Oct. 17)
- [x] Fixed problems with dragon knight dodge and hitbox issues (Oct. 17)
 
**Completion Deadline:** Oct. 17
 
# **Member**
- Chia-Chuan Tsou (Github: freshc0w)
