### ISSUE TITLE
[Team 1] New special feature mobs for waves

### ISSUE THREAD

**Issue by cindyle1** [UQcsse3200/2023-studio-3#237]
# **Description**
**Task:** [New special feature mobs for waves](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

These new mobs will have effects to differentiate themselves from the general melee and ranged mobs. Players will be able to distinguish each mob and plan towers according to the effect of that mob. So, the existing general mobs right now will just be basic melee or ranged mobs. 
 
## **Example**
- **Waves**: Depending on which wave, a specific feature mob will be spawned. E.g On wave 5, the dodging mobs will be spawned.

# **Dependencies**
- [x] Finalisation of mob packs
 
# **Milestones**
# Ice Planet
- [x] Revert existing mobs to be general melee and ranged (Oct. 10)
- [x] Implement splitting mob (Oct. 12)
- [x] Add animations (Oct. 13)
 
# Desert Planet
- [x] Revert existing mobs to be general melee and ranged (Oct. 10)
- [x] Implement dodging mob (Oct. 11)
- [x] Implement splitting mob (Oct. 12)
- [x] Add animations (Oct. 13)

# Fire Planet
- [x] Revert existing mobs to be general melee and ranged (Oct. 10)
- [x] Implement dodging mob (Oct. 11)
- [x] Implement splitting mob (Oct. 12)
- [x] Implement reflecting mob (Oct. 12)
- [x] Add animations (Oct. 13)

**Completion Deadline:** Oct. 15

 
# **Documentation**
- [NPC Factory](https://github.com/UQcsse3200/2023-studio-3/wiki/NPC-Factory)
 
# **Member**
- Wing Yan Lee (@cindyle1) (Cindy)
- Isaac Arli (@MiniSoda17)(Isaac Arli)
