### ISSUE TITLE
[Team 7] Fixing Hitboxes and Balancing Towers

### ISSUE THREAD

**Issue by ThivanW** [UQcsse3200/2023-studio-3#239]
# **Description**
**Task:** [Fixing Hitboxes and Balancing Towers](#).
**Feature:** [Enhancement on towers, new Towers and bomb ship](#181)

Some of the towers have a bigger hitbox than the tile upon which they are placed. This currently means that sometimes a tower cannot be placed next to another tile. This task aims to fix this issue and to balance the towers (in terms of fire rate, damage and cost) so that the player isn't overloaded with the number of projectiles on the screen at a time. 
 
# **Dependencies**
- [ ] The previously created towers need to be altered (#xx)
- [ ] The towers' fire rates needs to be proportional to the mobs' fire rates (#xx)
- [ ] The towers' damage will need to be changed to make up for the change of fire rate (#xx)
- [ ] The towers' cost will need to be balanced for the amount of mobs that spawn in a wave (#xx)
 
# **Milestones**
- [ ] Fix the hitboxes so that they match the tile size (Oct. 11)
- [ ] Talk to the mob team to figure out the balance for fire rate, damage and cost (Oct. 13)
- [ ] Alter the towers' fire rate (Oct. 17)
- [ ] Alter the towers' damage (Oct. 17)
- [ ] Alter the towers' cost (Oct. 17)
 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Thivan (@ThivanW) (Thivan Wijesooriya)
