### ISSUE TITLE
[Team-3] External UI Enhancement (Sprint-4)

### ISSUE THREAD

**Issue by aadityayadav17** [UQcsse3200/2023-studio-3#240]
# **Description**
In this sprint, our team will focusing on  enhancing the Main Menu, Settings, Story, Level Select, Help and End Game Screen.

# **Milestones**

 **Improvement to Main Menu Screen (Oct. 11)**
- [x] Design and add game title.
- [x] Readjust background.
- [x] Resize buttons according to the background.

#
 **Improvement the Help Section (Oct. 11)**
- [x] Add Help Screen for towers.
- [x] Add Help Screen for mobs.
- [x] Add Game Description screen.
- [x] Add How to Play screen.
#     
 **Improvement to Level Select Screen (Oct. 15)**
- [x] Add level descriptions.
# 
**Add loading screen (Oct 10)**
- [x] Implement async. code.
- [x] Add screen.
- [x] Add animation.
 #
 **Add win screens (Oct. 14)**
- [x] Make level win screen.
- [x] Make Overall win screen.
# 
- [x] **Make text and images on same screen in Story Screen (Oct. 14)**
- [x] **Refine code and remove smells (Oct. 15)**

**Completion Deadline:** Oct. 15

**Extras:**
If possible add:
-  Intro to game screen.
-  Make Transition effects for all screens.
- [x] Make a game tutorial.

# **Documentation**
- [MainMenuScreen](../wiki/MainMenuScreen)
- [SettingScreen](../wiki/SettingScreen)
- [GameCutsceneScreen](../wiki/GameCutsceneScreen)

# **Members**
- Gagandeep ( @Gaganx0 ) (Gagandeep Singh)
- Nidhi ( @Nidhidass1 ) (Nidhi Dass)
- Aaditya ( @aadityayadav17 ) ( Aaditya Yadav)
- Moksh ( @Moksh-Mehta7 ) ( Moksh Mehta)
- Rakshit ( @Octagunn ) (Rakshit)
