### ISSUE TITLE
Team 2 - Improvements on in-game buttons.

### ISSUE THREAD

**Issue by shiv-0831** [UQcsse3200/2023-studio-3#241]
# **Description**
**Task:** [Team 2] Improvements on in-game buttons.

The objective of this task is to implement in-game button animations and complete the remaining functionality of the timer button. The basic framework for all buttons in main game area has already been implemented. This task seeks to combine the timer button with the wave service and introduce button animations when a level commences.
 
## **Example**
**Button animations**
- The current implementation of buttons in the main game area is static. When a level commences, all the buttons are spawned without any indication.

 **Timer button**
- Currently deployed timer button is a static timer counting backwards from 1 minute and 40 seconds to however long the game runs. Integration with wave service will spawn the button only at the start of the game or when a wave finishes. Furthermore, when clicked, it will allow the player to skip the buffer period between consecutive waves.

# **Dependencies**

- [x] Implementation of wave service for timer button (#186 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Finish the functionality of timer button (11 Oct)
- [x] Add animations for in-game buttons (13 Oct)

**Completion Deadline:** Oct 15

 
# **Documentation**
Will be added when written
 
# **Member**
- Shivam (@shiv-0831) (Shivam Garg)
