### ISSUE TITLE
Wave Slider and Warnings

### ISSUE THREAD

**Issue by praneetdhoolia** [UQcsse3200/2023-studio-3#242]
# **Description**
**Task:** 

This task aims to implement a wave slider to indicate the progress the user had made so far on a particular planet, and a warning to inform the player of an incoming mob in any given lane.
 
## **Example**
- **Wave Slider**: The slider displays the percentage of waves that have been completed by the player so far on the specific planet.
- **Incoming Mob Warning**: The incoming mob warning is displayed briefly as an exclamation mark (the image displayed can vary based on the severity of the mob) immediately when a mob spawns in a lane.

# **Dependencies**
- [ ] #186 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Finalization of feature set (Oct. 11)
- [ ] Design and Implementation (Oct. 13)
- [ ] Testing and Integration in main (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- WIP
 
# **Member**
- @praneetdhoolia (Praneet)

**Comment by The-AhmadAA** [comment]
Slider implemented, warnings did not make it into final PR
