### ISSUE TITLE
[Team 5] Turret Select Screen Finalising

### ISSUE THREAD

**Issue by SonjaMcNeilly** [UQcsse3200/2023-studio-3#243]
# **Description**
**Task:** [Turret Select Screen Finalising](#243).
**Feature:** []()

This task will be about finalising the tower select screen. I received feedback from the studio that the red when selecting a turret is misleading and confusing since red typically indicates no, so I will be changing the colour to green to combat this. I will also be implementing a back button so the user has the option to go back to the level select screen. I will also implement a bar that will show all the selected turrets to provide a more visual indication of the turrets that are selected. I will also implement clicking sounds and hover sounds. If time permits, I will add a transition between the level select screen and the turret select screen to add juiciness,

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Replace Wall Icon with new Wall image (Oct. 11)
- [x] Change the select colour to green instead of red (Oct. 11)
- [x] Add clicking and hover sounds (Oct. 12)
- [ ] Implement a bar at the top indicating selected turrets (Oct. 12)
- [x] Implement same bar at the top of the screen of the main game (Oct.13)
- [x] Implement a go back button (Oct. 13)
- [x] Implement a transition between the level select screen and turret select screen (Oct. 16)
 
**Completion Deadline:** Oct. 16

# **Documentation**
- [Turret Selection Screen Wiki](Turret-Selection-Screen)

# **Member**
- Sonja McNeilly (SonjaMcNeilly) (Sonja McNeilly)
