### ISSUE TITLE
[Team 4] Level Completion Status

### ISSUE THREAD

**Issue by meganroxburgh** [UQcsse3200/2023-studio-3#247]
# **Description**
**Task:** [Level Completion Status].
**Feature:** [Levels and Mob Waves] (#183 )

Add in a detection for when the level has been completed (i.e. all waves have been defeated and there are no more mobs remaining). This should then transition to a level completed UI (to be completed by Team 3). We need to add in the logic to detect when the level has been completed.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x]  External UI Enhancement (#240 )
- [x]  WaveTask and WaveService (#186 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add in event listener to MainGameActions
- [x] Add in event trigger in MainGameScreen (link to lose screen and will be changed by team 3)
 
**Completion Deadline:** Oct 12
 
# **Documentation**
- [WaveService](https://github.com/UQcsse3200/2023-studio-3/wiki/WaveService)
 
# **Member**
- e.g. Megan Roxburgh (@meganroxburgh )
