### ISSUE TITLE
[Team 3] Maps Feature Ticket 

### ISSUE THREAD

**Issue by Gaganx0** [UQcsse3200/2023-studio-3#25]
# **Description**
Maps are the basis for the entire game to function, this ticket will lay out the feature set of various maps. The layout of the map will be an 8x20 grid, out of which 8x10 tiles from the left will be placeholders for the defense towers on the left side of the screen. The mobs would move right to left in the 8 fixed lanes. It's a top-down game so the camera would be fixed. 

## SubFeature/component
Visuals(1 member)-
Will handle everything you see on the map.

Grid management(2 members)-
Will handle placeholders and lanes.

Object management(2 members)- 
Will handle object placement into the placeholders making sure objects and mobs designed by other teams interact correctly with the map and other invisible objects.

(Once the grid and object parts are completed all members will join the visuals as these two mechanics stay the same across all levels and visuals would be changing.)

# Examples 
The map would pan out to be something similar to "plant vs zombies" as it is the original inspiration for the game. It will tie in to the game through the space theme visuals.

# **Dependencies**

Our work depends on the mobs(#4)  and tower(#5)  teams as the map will be the basis for their interaction.

# **Milestones**

- [x] The grid has been created with placeholders. (22 August)
- [x] Lanes, where mobs can move, have been created. (24 August)
- [x] Design the visual environment of the map. (26 August)

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**

-  Gagandeep( @Gaganx0 )(Gagandeep Singh)
-  Nidhi( @Nidhidass1 )(Nidhi Dass)
-  Aaditya( @aadityayadav17 )( Aaditya Yadav)
-  Moksh( @Moksh-Mehta7 )( Moksh Mehta)
-  Rakshit( @Octagunn )(Rakshit)

**Comment by Jonoym** [comment]
I've seen conflicting information about the map and how it might be bi-directional (monsters coming from both the left and right side). I'm not too sure what the studio has ended up on following but it might be good to clarify this before starting the sprint.

Aside from that, it looks good. It might need more information later on into the Sprint once you're sure of what changes will be required. Also don't forget to expand out the milestones and tasks into task tickets!

**Comment by The-AhmadAA** [comment]
> I've seen conflicting information about the map and how it might be bi-directional (monsters coming from both the left and right side). I'm not too sure what the studio has ended up on following but it might be good to clarify this before starting the sprint.
> 
> Aside from that, it looks good. It might need more information later on into the Sprint once you're sure of what changes will be required. Also don't forget to expand out the milestones and tasks into task tickets!

Hi Jono, the design committee met and discussed map design - The wiki has been updated to reflect this and this feature ticket is in line with that as far as I can tell.
