### ISSUE TITLE
[Team-3] Main Menu, Settings Screen & Level Lock on LevelSelectScreen

### ISSUE THREAD

**Issue by aadityayadav17** [UQcsse3200/2023-studio-3#250]
# **Description**
**Task:** UI & Animation Enhancements
**Feature:** [External UI Enhancement (Sprint-4)](#240)

The tasks in this ticket aim at improving the game's UI. These include introducing a level lock on LevelSelectScreen & fixing resizing issue of MainMenu and Settings Screen.
 
# **Milestones**
- [x] Add Title on MainMenuSceen (Oct. 13)
- [x] Fix resizing issue on MainMenuScreen (Oct. 13)
- [x] Fix resizing issue on SettingsScreen (Oct. 13)
- [x] Reduce recurring code on MainMenuScreen (Oct. 13)
- [x] Add Level Lock on LevelSelectScreen (Oct. 15) 
- [x] Fix Story Screen (Oct. 17)
 
**Completion Deadline:** Oct. 17

# **Documentation**
- [UI](../wiki/UI)
- [Animations](../wiki/Animations)
- [Settings](../wiki/Settings)
- [New Levels Task](../wiki/New-Levels-Task)
 
# **Member**
- Aaditya (@aadityayadav17) (Aaditya Yadav)
