### ISSUE TITLE
Team 3 UI Screens 

### ISSUE THREAD

**Issue by Moksh-Mehta7** [UQcsse3200/2023-studio-3#251]
# **Description**
**Task:** UI Levels Switch , lose and Win screens 
**Feature:** [External UI Enhancement (Sprint-4)](#240)

Task to create level switch screen, win screen and improve the lose screen 
 

# **Dependencies**
Triggers for the next level and wins screens by wave team.

# **Milestones**
- [x] create a basic switch screen  (Oct. 13)
- [x]  create a basic Win screen (Oct. 13)
- [x] Add triggers to switch and win screens  (Oct. 13)
- [x] Improve both screens (Oct. 13)

**Completion Deadline:** Oct. 15

 
# **Documentation**
- [UI](../wiki/UI)
 
# **Member**
- Moksh Mehta (@Moksh-Mehta7 ) (Moksh Mehta)
