### ISSUE TITLE
[Team-3] Planet select screen improvements 

### ISSUE THREAD

**Issue by Octagunn** [UQcsse3200/2023-studio-3#252]
# **Description**
**Task:** [Improvement to the Planet Select screen].
**Feature:** [ External UI Enhancement (Sprint-4)](#240 )

The task aims to Improve the planet select screen which serves as the level selection screen of the game in this new features such as the planet description will be added as well as general bugs that are present will be fixed 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] addition of planet description (Oct. 14)
- [x] addition of general aesthetic improvements (Oct. 14)
- [x] Fixing the planet select  (Oct. 15)
- [x] General bug fixes (Oct. 15)
 
**Completion Deadline:** Oct.16
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Rakshit Nandal (@Octagunn ) (Rakshit)
