### ISSUE TITLE
Team 2 - Camera Shaker and Tile Highlighting 

### ISSUE THREAD

**Issue by Mohamad11Dab** [UQcsse3200/2023-studio-3#259]
# **Description**
**Task:** Implement Camera Shaker and Tile Highlighting 

This task will involve the implementation of two significant features. Firstly, a Camera Shaker module will be created to simulate screen shaking once A mob boss has been spawned, adding an exciting visual effect to the game. Secondly, tile highlighting will be improved. Tiles will only be highlighted when a tower is selected. If the user can afford the selected tower and there are no other entities on that tile, it will be highlighted in green. If there is another entity present or insufficient resources, it will be highlighted in red.

# **Milestones**
- [x] Implement Camera Shaker module (By Oct 10).
- [x] Integrate Camera Shaker with MapService (By Oct 12.).
- [x] Enhance tile highlighting logic (By Oct 14).
- [x] Write Tests and Documentation (By Oct 16).
- [x]  Fix some code smells (By Oct 16.). 

**Completion Deadline:** Oct 17

# **Documentation**
- [Camera Shaker Module Documentation](https://github.com/UQcsse3200/2023-studio-3/wiki/CameraShaker)
- [Tile Highlighting Documentation](https://github.com/UQcsse3200/2023-studio-3/wiki/Tile-Highlighting)

# **Member**
- Mohamad (@Mohamad11Dab) (Mohamad Dabboussi)
