### ISSUE TITLE
[Team 7] Boss Spawning And Lose Condition

### ISSUE THREAD

**Issue by ThivanW** [UQcsse3200/2023-studio-3#26]
# **Description**
**Task:** [Boss Spawning And Lose Condition](#26).
**Feature:** [Boss Mobs](#2)

The bosses will spawn in after a few waves and will move towards the ship. Once they reach the ship they will trigger the lose condition and end the game. 
 
# **Dependencies**
- [ ] The bosses will spawn along with general mobs (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Figure out the spawning mechanic of waves with the general mob team (Aug. 19)
- [ ] Get the bosses to spawn in at the right time (Aug. 22)
- [ ] Make sure the game ends when the bosses reach the end goal (Aug. 25)
 
**Completion Deadline:** Aug. 25
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Deven (@dbhasin4123) (Deven)
