### ISSUE TITLE
[Team 5] Engineer Improvements

### ISSUE THREAD

**Issue by ryandmcneilly** [UQcsse3200/2023-studio-3#260]
# **Description**
**Task:** [Engineer Improvements](#260).
**Feature:** [x](#x)

Currently, engineers are in a state that needs some modifications in order to be completed. There are currently some major bugs surrounding engineers, where engineers are currently moving to either the top or the bottom of the screen when they are moving around the map. Engineers also get stuck in a state of firing, when it appears there are no mobs in vision. Engineers also were originally meant to come in an "RTS" format, but currently it has steered away from that path. This task ticket will fix the above bugs, and improve gameplay functionality for the engineers. 
 
## **Example**
- **Engineer Wandering**: Engineers will correctly wander around the map, and not always clump together.
- **Movement**: Engineers will be able to freely move around the map, without being restricted for the menu.

 
# **Milestones**
#### Goal 1 (Oct 8): Planning and Scaffolding 
- [x] Design necessary improvements for the engineers
- [x] Identify bugs for the engineers

#### Goal 2 (Oct 14) Code Implementation 
- [x] Free movement of engineers (remove the need for menu)
- [x] Increase time between engineers spawning, so they don't all spawn at once
- [x] Fix the bug where engineers move to the top and bottom of the screen
- [x] Fix the bug where engineers keep shooting after killing a unit
- [x] Fix issue where more engineers than the Engineer Count appear

#### Goal 3 (Oct 16) Testing and Debugging (JUnit); Integration
- [x] Design and implement a testing suite
- [x] Debug faulty code
- [x] Implement interaction with currency functionality

#### Goal 4 (Oct 17) Documentation
- [x] Document code and testing suite
 
# **Documentation**
- TBD
 
# **Member**
- Ryan (@ryandmcneilly ) (Ryan McNeilly)
- Nawal (@nawal-0) (Nawal)

**Completion Deadline:** Oct. 17
