### ISSUE TITLE
Team 4 - update waves

### ISSUE THREAD

**Issue by samsully** [UQcsse3200/2023-studio-3#262]
# **Description**

A one paragraph description of the task on which you will work. It should briefly explain what will be done (e.g. "Implement an armour component"). This includes textual explanations of the work. (e.g. "`Armour` inherits from `Component` and will add an event handler to the player entity so that the armour takes damage rather than the player. Different types of armour will have different durability. Once the armour is broken (durability reaches zero), it will no longer take damage and more attacks on the player will cause it to lose health.")

The design committee requested a redesign of the waves, and with the addition of the new mobs, the wave factory requires reimplementation. This is to help with the visual progression of the game, and ensure the game advances in difficulty in multiple ways: health, damage, number of mobs and the abilities of each mob. 

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] New mobs implementation
- [x] Design committee wave design
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design the new waves structure
- [x] Ensure the new mobs are spawn able 
- [x] Implement the new wave structure
- [x] alter the tests
- [x] impliment the trigger of the screen shake for the boss
 
**Completion Deadline:** 17th October
 
# **Documentation**
 
# **Member**
- Samantha Sullivan (@samsully)
