### ISSUE TITLE
[Team 5] Mob Drop

### ISSUE THREAD

**Issue by Hasakev** [UQcsse3200/2023-studio-3#28]
# **Task Ticket: Income on Mob Drop Implementation**

**Task:** Income on mob drop (including graphic that you click)
**Feature:** Economy (#15)

## **Description**
Implement the income generation mechanism when mobs are eliminated. This mechanism will involve creating a visual representation of the income drop (i.e., scraps) from the mobs and allowing the player to click on it to collect the income. This functionality contributes to the overall economy system, where players can earn currency through enemy eliminations.

## **Example**
When a mob is defeated, a graphical representation of scraps should appear at the location where the mob was defeated. The player can click on the graphic to collect the income, which will then be added to their total currency balance.

## **Dependencies**
This task relies on the implementation of the basic mob class (#23) and the implementation of the basic economy class (#19). 
> Note: the "scraps" class can be implemented independently first. 👍

## **Milestones**
List of steps that need to be completed for this task.

#### Goal 1 (Aug 20): Planning and Scaffolding 
- [x] Plan out and communicate with other teams (specifically #4) on how to implement the feature with the base mob class (#23)
- [x] Design and plan the visual representation of income drop (graphic) when mobs are eliminated.

#### Goal 2 (Aug 23) Code Implementation and Test Design (JUnit)
- [x] Implement the visual representation of income drop when mobs are eliminate
- [x] Implement the interaction mechanism for collecting the income (by clicking on the scrap)

#### Goal 3 (Aug 26) Testing and Debugging; Integration
- [x] Test the income drop mechanism in different scenarios, ensuring correct income calculation.
- [x] Debug and refine the interaction mechanism for collecting income.

#### Goal 4 (Aug 28) Documentation
- [x] Document the implementation details of the income on mob drop mechanism.
- [x] Update relevant documentation to reflect the changes made.

**Completion Deadline:** Aug. 30

> If time is still available, implement scrap drops for the "currency generating turret".
> The intention is to be able to use the base "scrap" class to have other mob drops in the future.

## **Documentation**
- [Main description of feature](../wiki/EconomySystem)
- [User documentation](../wiki/Economy)

## **Member**
- Kevin (@Hasakev) (Kevin Luo)
