### ISSUE TITLE
[Team 4] Mob movement task

### ISSUE THREAD

**Issue by bojyyy** [UQcsse3200/2023-studio-3#29]
# **Description**
**Task:** Mob movement(#29)
**Feature:** General Mobs(#4)

This task will implement basic movement for the game's mobs. The mobs will move from the right hand side of the screen towards the player's towers which will be situated on the left. This movement will run parallel to the horizontal and vertical axes of the grid, allowing the mobs to either move directly towards the player's side or change lanes.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Mob Entity Base Class (#23)
- [x] Grid tiles to constrain a mob's movement (#27)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial design of movement mechanics (Aug. 19)
- [x] Unit tests implemented  (Aug. 23)
- [x] Mob movement implemented and tested (Aug. 25)
- [x] Wiki documentation updated (Aug. 23)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Main description of feature](../wiki/Game-Features)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Miles Bojorge (@bojyyy)
