### ISSUE TITLE
Tower sounds(Team-7)

### ISSUE THREAD

**Issue by karthikeya-v** [UQcsse3200/2023-studio-3#293]
# **Description**
**Task:** Adding sounds to towers.

Add different sounds to different towers with moderation check for the game aesthetics with sound and fix bugs in the code.
 

e.g.
- [ ] Add sounds to all the existing towers
- [ ] look for testing changes to make to include these new sounds in testing
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1: procure sounds
- [ ] Step 2: add sounds
- [ ] Step 3: modify tests
- [ ] Step 4: create documentation
 
**Completion Deadline:** oct 17

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
-karthikeya vemulapalli (@karthikeya-v ) (@karthik)
