### ISSUE TITLE
[Team 4] Bug Fixes & Code smell fixes

### ISSUE THREAD

**Issue by max9753** [UQcsse3200/2023-studio-3#295]
# **Description**
**Task:** Bug Fixes & Code smell fixes
**Feature:** Team 4 Levels & Wave Improvements.

This task was all about fixing the 1.2k code smells that the project had after sprint 3. We had several bugs & several smells in the code that team 4 had worked on and aimed on fixing a good chunk of those as well as investigating several bugs with tests and code we had discovered.

# **Dependencies**
This task did not really have any dependencies as it was mostly maintenance to existing code and files.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Reduce Code smells in files created for wave management (Oct 15th)
- [ ] Reduce code smells in files created for level management (Oct 17th)
- [ ] Document changes & fixes (Oct 17th)
- [ ] Fix any bugs that can be fixed before the deadline (Oct 17)
 
**Completion Deadline:** Oct 17th

 
# **Member**
- Max Taylor (@max9753)
