### ISSUE TITLE
[Team 4] Mob Interactions with Towers via Projectiles

### ISSUE THREAD

**Issue by meganroxburgh** [UQcsse3200/2023-studio-3#31]
# **Description**
**Task:** [Mob Interactions with Towers ](#).
**Feature:** [General Mobs](#4 )
This task will implement how the mobs will interact with tower entities in the game. Mobs will move across the map and when they are within a certain x-coordinate distance of a tower, they will shoot their projectile to attack that tower. An event handler will be used which will be triggered when the mob is within a certain radius of the tower. If it is not yet within this radius, then it will not shoot its projectile and will continue to move forward through the map.
 
## **Example (optional)**
- The mob will be moving along their lane and for example, when they are 3 (this value may change) grid squares, away from a placed tower entity, the mob will begin shooting its projectile at the tower, causing the tower to take damage. If enough damage is taken, then the tower will be removed from the game.  

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

This task is dependent on the mob movement (#29 ) and mob entity base class creation (#23 ). Once the initial functionality has been implemented, which causes some action to occur when the mob is within a certain radius of another object, this task will need to be incorporated with the tower interactions (#11 ) and projectiles (#7 ). 

- [x] Mob Entity Base Class Creation (#23 )
- [x] Mob Movement (#29 )
- [x] Tower Interactions (#11 ) 
- [x] Projectiles (#7 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial creation, alter the current ChaseTask to make the ghosts perform a different task (print) when they are in range of the player (Aug. 25)
- [x] Remove the chase task functionality so ghosts only cause the print statement and no longer chase when in range (Aug. 25)
- [x] Initial testing of altering the ChaseTask (Aug. 25)
- [x] Wiki documentation for altering the ChaseTask (Aug. 25)
- [x] Incorporate with the mob base entity class rather than the ghost entity (Aug. 26)
- [x] Testing with the mob base entity class (Aug. 26)
- [x] Wiki documentation for incorporation with mob base entity class (Aug. 26)
- [x] Incorporate with mob movement (Aug. 27)
- [x] Testing with mob movement (Aug. 27)
- [x] Wiki documentation for general mobs (Aug. 27)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [[Main description of feature](https://github.com/UQcsse3200/2023-studio-3/wiki/Game-Features))
- [JavaDoc](JavaDoc/Location/Package/Class)

# **Member**
- Megan Roxburgh (@meganroxburgh ) (Megan Roxburgh)
- Max Taylor (@max9753 ) (Max T)
