### ISSUE TITLE
[Team 4] Production of an Alien Mob Graphic

### ISSUE THREAD

**Issue by BlairCannon97** [UQcsse3200/2023-studio-3#32]
# **Description**
**Task:** [Production of Alien Mob Graphics](#3).
**Feature:** [General Mobs](#2)

This task will focus on the creation of the visual aspects of a single alien mob. First, the design committee will be consulted to find the best suited theme given the game theme. Different asset packs from the game art style guide will be taken into consideration when seeking a general mob theme. Once a theme has been agreed upon, a pack of assets will be produced which will include the graphic elements for a single mob. This task will conclude with the implementation of those graphics.
 
## **Example (optional)**
- The first mob will include a walking animation as it approaches a tower, some visual indication to suggest it has taken damage, and an animation for when it fires a projectile.

# **Dependencies**
- The colours, design and theme will depend on the art direction decided by the Design Committee.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Consult the design committee and agree on a theme for the entity (And future entities in general) (Aug. 19)
- [x] Explore all options (likely existing asset packs) to find the best suited entity visual assets for the game (Aug. 21)
- [x] Implement the visual assets on a single mob, verify functionality (Aug. 25)
 
**Completion Deadline:** Aug. 25

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (BlairCannon97) (Blair Cannon)
