### ISSUE TITLE
[Team 3]Map object management  

### ISSUE THREAD

**Issue by Moksh-Mehta7** [UQcsse3200/2023-studio-3#33]
# **Description**
**Task:** object management.
**Feature:** Maps feature ticket.(#25)

The task is to create placement for visible and invisible objects on the map like places for decorations(plants, stones etc.), menu buttons, mob generator and also set the invisible map boundary. 

# **Dependencies**

- [x]   UI implementation(#18 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Map clean Up (Aug 20)
- [x] create placeholders for immovable artifacts and menu buttons(Aug 22)
- [x] create placeholder for mob generator(Aug 27)
- [x] set map boundary (Aug 28)

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**

Aaditya( @aadityayadav17 )(Aaditya Yadav)
Moksh( @Moksh-Mehta7 )(Moksh Mehta)
