### ISSUE TITLE
[TEAM 6]

### ISSUE THREAD

**Issue by ElanagaiArivuchelvan** [UQcsse3200/2023-studio-3#34]
# **Description**
The team 'Features' are to create Interfaces in the game to make interaction with the players more interesting and to facilitate the start of the game by click and push option buttons.
The current Ideation is to allow the player to be able to navigate inside the game and figure out the build mechanics of the game and storyline.
The team is also responsible for the tower pop up placements and the defensive walls placements.

## **Examples (optional)**
- START:  When you enter to the game this UI will enable you to access the game and actually begin playing it
- MAIN MENU: This Interface will direct you to options such as Settings,help,levels,Restart and Resume
- BUILDINGS: This is basically the placements and seem Interface which determines the positions and themes of 
                        the buildings placed in the game environment. Not only buildings this includes the defensive walls 
                        for the game and positions of all other extra implementations.

# **Dependencies**

1) Relies on Map team for the placements ( #33 )
2) Design committee, for the context and theme of buildings and types of them 

# **Milestones**

- [ ]  Brainstorm and pick the theme and the type of buildings and placements the Interface should Implement (Aug. 20)

- [ ] Implement the design for creating the start button and main menu with accordance to the theme (Aug. 23)

- [ ] Design and place various buildings in the platform once the map team concludes their idea of surroundings (Aug. 26)

**Completion Deadline:** Aug. 30

# **Members**

- Elanagai Arivuchelvan (@ElanagaiArivuchelvan)
- Rahul Sagar Pabba (@rahulsagar500)
- Vansh Mittal (@V4N5HM)
- Jigyasu Mittal (@JigyasuMittal)
- Sahajdeep Singh (@Sahajdeep31)
