### ISSUE TITLE
Buildings placement - [Team 6]

### ISSUE THREAD

**Issue by ElanagaiArivuchelvan** [UQcsse3200/2023-studio-3#35]
# **Description**
**Task:** [Placement of Buildings ](#3).
**Feature:** [Interfaces and Game Environment](#2)

The fixed position of buildings will be done at the end, where the task is completed and merged bug free. This task involves coordinating data from various teams to be based on the same theme and further Integrating all the knowledge acquired to create a seamless environment and an interactive platform for the users.

## **Example (optional)**
- **Buildings**: For creating the Game Environment, this feature of placing Buildings will be very Interactive as the user will be able to visually imagine the surroundings and emotionally connect with the game.
-  **Defensive Walls**: This would be an integral part of the game as it's based on defensive mechanisms and fights with accordance to the storyline

# **Dependencies**
- [The placements of towers and turrets are needed so that the position coordinated of buildings don't clash] #6 
- [The lanes and grid positions are needed to type in the coordinates for the placement] #25 
- [ The input from design committee is also an Integral part so as to design the buildings and the theme] #Design committee

# **Milestones**
List of steps that need to be completed for this task.

- [x]   Research on the various created games and collect data on types of buildings and fixed positioned particulars in the game environment (Aug. 22)
- [x]  Short list the most feasible type of buildings according to the game in studio3 as per all inputs from dependent teams and select the final design based on the research data (Aug 24)
- [x]  Implement the features (Aug 25)
- [x] check for any merge conflicts or bugs and correct it after which merge them to the main branch (Aug 26)

**Completion Deadline:** Aug. 26

 
# **Documentation**
- [Main description of feature] (../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Elanagai Arivuchelvan (@ElanagaiArivuchelvan)
- Rahul Sagar Pabba (@rahulsagar500)

**Comment by The-AhmadAA** [comment]
This ticket closed as this feature implemented in #207
