### ISSUE TITLE
Start page Interface and options creation - [Team 6]

### ISSUE THREAD

**Issue by ElanagaiArivuchelvan** [UQcsse3200/2023-studio-3#36]
# **Description**
**Task:** [ Start button and Interface](#3).
**Feature:** [Interface and Game Environment](#2)

Start option is the foremost feature any user will encounter before beginning any type of software design including a game, which is why this implementation is taken into account and worked on as well like how any other part of the game is done. Once entering into the game environment, another major task is in when the users are new and are trying to get used to the environment for which they need various other options such as help, how to use etc. Even a generic player needs facilitations such as current level, settings,how to play options in the game, which will all be implemented at the end of completing this Task ticket.
This task also involves the design of the game logo along with placing it in the start page of the game
 
## **Example (optional)**
- **Start**: To allow the user to enter into the gaming Environment
- ** other options to be split as**

1. **Quit** : This option would enable to exit the game environment
2. **How to play**: This option would contain the storyline of the game explained and then would enhance a small tutorial of the game if user enables it and it contains the basic game play written in a default page
3. **Settings**: Feature where all basics such as volume and network adjustments and shortcuts are mentioned and viewed

# **Dependencies**

- [The whole game , as tutorial is based on the game ]  @UQcsse3200/2023-studio-3 
- [Design committee for the theme of buttons] (#design committee)

# **Milestones**
List of steps that need to be completed for this task.

- [x] Research of how the options can be optimised by comparing other games   (Aug. 21)
- [x] Implementational design of start button (Aug. 23)
- [x] Design of the start logo (Aug 25)
- [x] Implementational design of all main menu options  (Aug. 27)
- [x] Error checking (Aug 28)
- [x] Committing the final work (Aug 29)

**Completion Deadline:** Aug. 29

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jigyasu Mittal(@JigyasuMittal)

**Comment by ElanagaiArivuchelvan** [comment]
Updated the start screen with the background image we had opted for but had a few issues regarding resolution which was the reson for not delivering this background in sprint 1. This issue was sorted and deliverd for sprint two

- [ ] Scifi background changed for sprint 2

**Comment by ElanagaiArivuchelvan** [comment]
Updated the start screen with the background image we had opted for but had a few issues regarding resolution which was the reson for not delivering this background in sprint 1. This issue was sorted and deliverd for sprint two

 Scifi background changed for sprint 2
