### ISSUE TITLE
[Team 2] Tower Physics

### ISSUE THREAD

**Issue by praneetdhoolia** [UQcsse3200/2023-studio-3#37]
# **Description**
**Task:** Tower Physics
**Feature:** [Team 2] Towers Feature Ticket #5

This task involves creating tower hitboxes, enabling tower interactions with projectiles and enemy attacks and entities, and displaying visual effects for towers during these events. Once successfully implemented, towers should be able to deal damage to enemies, take damage from enemy melee/projectiles, fire projectiles against enemies, block enemies from proceeding further along their path, and trigger visual effects/animations for these events.

 **Note:** All visual effects and animations will be handled by **[Team 2] Towers' Graphics and sound #9**.

## **Features**

- **Projectile Interaction**: The tower fires a projectile when a mob is available as a target. This involves deciding the projectile's attributes (Eg: Direction, Type, Frequency, etc.), and triggering a visual animation for the firing routine.
- **Mob Interaction**: Towers can block mobs from proceeding further along their path, forcing them to attack the tower using melee/projectile attacks. Certain towers may have additional features to deal damage to the mobs during this interaction.
- **Defense Interaction**: Towers will reduce their health or other attributes accordingly when an enemy mob/projectile interacts with the tower hitbox. They may trigger certain effects/animations when attacked or destroyed.

# **Dependencies**

- [x] [Team 1] Single-target projectiles (#8)
- [x] [Team 1] Multi-target projectiles (#12)
- [x] [Team 2] Tower entity creation (#6)
- [x] [Team 2] Towers' Graphics and sound (#9)
- [x] [Team 4] Mob Interactions with Towers (#31)

# **Milestones**

- [x] Projectile fire routine (Aug. 20)
- [x] Enemy mob/attack interaction (Aug. 20)
- [x] Events to trigger animations (Aug. 23)
- [x] Sprint 1 finalization and testing (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Members**
- Praneet Dhoolia (@praneetdhoolia)

**Comment by The-AhmadAA** [comment]
Created events to trigger animations (and other things) via an AITaskComponent - refer to #9 Tower Graphics and Sound task

**Comment by The-AhmadAA** [comment]
Most tasks covered by other teams or task tickets
