### ISSUE TITLE
[Team 3] Visuals 

### ISSUE THREAD

**Issue by Octagunn** [UQcsse3200/2023-studio-3#38]
# **Description**
**Task:** [Visual implementation](#3).
**Feature:** [Maps feature ticket](#25 )

this task is to create and implement the various background and aesthetic visuals that can be seen by the player 

# **Dependencies**

- [x] Interface needs to be in line with the overall aesthetic of the game  (#34)
- [x] the towers should be in line with the overall aesthetic of the game (#9  )
- [x] Mobs should be in line with the general aesthetic of the game (#4 )
- [x] Boss mobs should be in line with the general aesthetic of the game (#10 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] implement the visual background of the level map (Aug. 24)
- [x] fix and improve along with tweak the general aesthetic of the level map to that of the game (Aug. 25)
- [x]  fix and improve any underlying issues (Aug. 26)

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Rakshit Nandal (@Octagunn ) (Rakshit Nandal)
