### ISSUE TITLE
[Team 2] Tower entity creation

### ISSUE THREAD

**Issue by Mohamad11Dab** [UQcsse3200/2023-studio-3#6]
# **Description**
**Task:** Create Tower Entity. (#6).
**Feature:** Tower Feature Ticket (#5)

The task involves the creation of a Tower entity designed to serve as a defense structure within the game. This tower will be responsible for protecting the engineers by eliminating the aliens. The Tower will be stationed on specific tiles that are marked unavailable for other use. Interactions with the tower, such as its deployment or upgrades (for future sprints), will be facilitated through the game's user interface. The entity will have specified health, and its establishment or upgrade will lead to a deduction of in-game cash. 
 
## **Example (optional)**

**Functionality:** Players will have the option to place the tower on certain tiles to safeguard the engineers & resources. This tower will automatically target and attack alien invaders within its range.

# **Dependencies**

- [x] Tile marking mechanism to designate specific tiles as tower placement spots (#25)
- [x]  facilitate placement or upgrade processes of towers in terms of health, range and cost). (#15 & #7)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Collaborate with the map team & economy team to understand the tile marking system and economy management system (Aug. 22)
- [x] Collaborate with projectile team to integrate tower with projectile (Aug 22)
- [x] Implement the Tower entity with the desired attributes and functionalities (Aug. 24)
- [x] Testing and documentation of the implemented tower entity and its associated mechanisms (Aug. 28)
 
**Completion Deadline:** Aug. 29

 
# **Documentation**
- [Tower Factory](https://github.com/UQcsse3200/2023-studio-3/wiki/Tower-Factory)
- [JavaDoc](https://uqcsse3200.github.io/2023-studio-3/com/csse3200/game/entities/factories/TowerFactory.html)
 
# **Member**
- Mohamad Dabboussi (@Mohamad11Dab ) (Mohamad Dabboussi)
- Shivam Garg (@shiv-0831) (Shivam Garg)

**Comment by Mohamad11Dab** [comment]
updated some dependencies (tagged the relevant tickets )

**Comment by Mohamad11Dab** [comment]
I've developed the `TowerFactory` class which includes a base function to produces a standard tower entity, intended to serve as a foundational entity for more specialized tower creation processes. I've also integrated the `CostComponent` to cater to entities requiring cost allocation, typically for towers. Additionally, I've set up blank files: `baseTowerConfigs` (located at: `entities/configs`) and `tower.json`, which are earmarked for storing tower properties and subsequently loading them into `TowerFactory`. For a comprehensive understanding of configuration, please refer to the "Configuring Entities" section on the wiki.

**Comment by Mohamad11Dab** [comment]
Added JUnit tests for `TowerFactoryTest` and `CostComponentTest`

**Comment by Mohamad11Dab** [comment]
All tasks are done.
