### ISSUE TITLE
[Team 1] Projectiles

### ISSUE THREAD

**Issue by MiniSoda17** [UQcsse3200/2023-studio-3#7]
# **Description**
In this first sprint, our team will be focusing on creating the base functionality of projectiles that will be used by towers and mobs. We will be focusing on this like collision, speed, and direction. Our completed single-target projectile will move linearly in one direction and stop when coming into contact with other objects (mobs). On top of this, we will also be adding the base functionality of AOE effects which can be added to projectiles and towers. We will be focusing on making sure that the code we write for projectiles and AOE effects can be easily reusable so that other feature teams can use our base functionality. For example, the mob feature team will be able to use our projectile class and fire back at towers and the other tower feature team can use our AOE effects for their towers. It should also be scalable so that when difficulty ramps up, we can easily change things such as speed and frequency.

### Collision - @freshc0w 
Adding the collision mechanics of the projectiles so that they will have a hitbox.

### Single-target Projectile - @MiniSoda17 & @cindyle1 
Adding the base mechanics for all projectiles within the game

### AOE Effects- @gregchan550 & @freshc0w 
Adding the base mechanics for AOE effects within the game

### Multi-target Projectiles - @JSLLW 
Extending the functionality of single-target projectiles to be able to have multiple targets.

## **Examples (optional)**
- **Single-target projectiles**: The base class for projectiles will only be able to attack a single target and will disappear on contact.
- **Multi-target projectiles**: 
- **AOE**: Area of Effect attacks will linger for some time and cover one or more tiles while dealing a type of effect over time e.g. slow, damage, stun.
# **Dependencies**

- Projectile collision will rely on mob collision mechanics(#4)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Finalise UI, design, and effects of all projectiles and AOE effects (Aug. 17)
- [x] Have our collision mechanics for the projectiles fully implemented (Aug. 21)
- [x] Our single-target projectiles fully working in the game (Aug. 23)
- [x] #12 (Aug. 25)
- [x] Create our base AOE effect class (Aug. 25)
- [x] Collaborate with Team 2 and make sure that towers can create and fire projectiles (Aug. 27)
- [x] Making sure that all sub-features work together well and collision mechanics work when in contact with mobs (Aug. 29)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Adding a slow effect
- [ ] Adding fire effect

# **Documentation**
- [Main description of feature](../wiki/Game-Features)
- [User documentation](../wiki/User-Documentation)

# **Members**
- Isaac Arli (@MiniSoda17) (Isaac Arli)
- Chia-Chuan Tsou (@freshc0w ) (Chia-Chuan Tsou)
- Wing Yan Lee (@cindyle1 ) (Cindy)
- Gregory Chan (@gregchan550) (Gregory)
- Josephine Wong (@JSLLW ) (s4528565@student.uq.edu.au)

**Comment by freshc0w** [comment]
Hi, 
I'm a bit confused with the assignment I'm tasked with. I understand I have to deal with the overall hitbox and interaction between other entities of the projectile but doesn't **collision** encompass the effects applied as well? (i.e. dmg dealt and/or slow effects). If so, can I rename my task to be the "Projectile interaction with enemies." As we discussed in our meetings, I can then also focus on experimenting with projectiles that disappears upon contact, causing a localized splash damage area that effects nearby enemies and/or focus on a dampening effect even after collision with an enemy that affects subsequent enemies. I understand this might cause some overlap between the AOE effects with @gregchan550 so I'm more than happy to pair up with him on this comprehensive task.

**Comment by freshc0w** [comment]
Also, I think we should also have someone focusing on the "projectile generation and behavior" aspect. They can implement a dynamic projectile firing system that allows projectile to be launched from towers at a periodic interval. Can also establish a starting pivot point at the launching site, allowing projectiles to be fired at different angles based on the desired input.

Also what about the UI, design and sound effects of the projectile and it's impact on other entities. There's going to be different types right? Should we also allocate someone for this?

ALSO, **I think we should also consider the adaptability and scalability of said effects so it may be reused and altered for other situational purposes. (i.e. mobs shooting projectiles back or the ramping difficulty of the game.)** and add this in our feature description.

That's it I promise.. Sorry team lol

**Comment by MiniSoda17** [comment]
Hello @freshc0w, 

You do bring up some important points and we have made these changes to the Feature ticket. Thank you for your input.
