### ISSUE TITLE
[Team-3] Maps Feature Ticket (Sprint-2)

### ISSUE THREAD

**Issue by aadityayadav17** [UQcsse3200/2023-studio-3#73]
# **Description**
In this sprint, we will be fixing grid tile count, resetting boundaries, aligning lane heights, and adding a non-conflicting map background. These adjustments will enhance gameplay alignment, visual cohesion, and overall aesthetics.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Fix the number of tiles with respect to the grid (Sept. 2)
- [x] Reset the grid boundaries (Sept. 4)
- [x] Fix lane heights in accordance to mob & tower heights (Sept. 6)
- [x] Implement the map background, so it doesn't conflict with overall aesthetic (Sept. 8)

**Completion Deadline:** Sept. 9

# **Extras (optional)**
- [ ] If possible, implement non-static background.

# **Documentation**
- [Game Screen](../wiki/Game-Screens)
- [Game Area](../wiki/Game-Areas)

# **Members**
-  Gagandeep ( @Gaganx0 ) (Gagandeep Singh)
-  Nidhi ( @Nidhidass1 ) (Nidhi Dass)
-  Aaditya ( @aadityayadav17 ) ( Aaditya Yadav)
-  Moksh ( @Moksh-Mehta7 ) ( Moksh Mehta)
-  Rakshit ( @Octagunn ) (Rakshit)
