### ISSUE TITLE
[Team 1] Projectile animations

### ISSUE THREAD

**Issue by cindyle1** [UQcsse3200/2023-studio-3#74]
# **Description**
**Task:** [Projectile Animations]().
**Feature:** [Projectiles](#7 )

The projectiles will need to use Atlas to implement changes in the animation. This includes explosions, angle of fireball when being shot, and smoke. To do this the projectile class will call the animation component from the atlas file. For this sprint the single projectile's animations will be focused on which can then be replicated for other effects.

# **Dependencies**

- [x] Image packs need to be finalised
- [x] Making sure that towers can create and fire projectiles (#5)
- [x] Projectile factory working 
- [ ] Mobs damage animation implemented to add sound effect for on collision
 
# **Milestones**
List of steps that need to be completed for this task.

@cindyle1 
- [x] Finalise image package for the single projectile (Aug. 31)
- [x] Add animation for single-target (Sep. 07)
- [x] Add animation to mob-King projectiles (Sep. 08)
- [x] Add animation for burn effects (Sep. 9)
- [x] Add animation for stun effect (Sep. 9)
- [x] Add animation for fireworks effect (Sep. 10) 
- [x]  Add animations for pierce effect (Sep. 10)

@MiniSoda17 
- [x] Add new design for mob projectiles (Sep. 07)
- [x] Add animation to mob projectiles (Sep. 08)
- [x] Add design for engineer projectiles (Sep. 08)
- [x] Add animation for engineer projectiles (Sep. 09)
- [x] Add animation for snowball effects (Sep. 10)
- [x] Add design for pierce effect (Sep. 10)

Extra
- [ ] Add Parabolic animation 
- [ ] Add sounds effects (Sep. 10)

**Completion Deadline:** Sep. 11
 
# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2023-studio-3/wiki/Projectile-Animation-Component)
- [JavaDoc](https://uqcsse3200.github.io/2023-studio-3/)
- ...
 
# **Member**
- Wing Yan Lee (@cindyle1) (Cindy)
- Isaac Arli (@MiniSoda17)(Isaac Arli)
