### ISSUE TITLE
[Team 4] General Mobs Improvements

### ISSUE THREAD

**Issue by meganroxburgh** [UQcsse3200/2023-studio-3#76]
# **Description**
In Sprint 1, we created the general mobs base class and implemented the moving and task for them to shoot projectiles. We also implemented a test sprite (Xeno Grunt) to display during gameplay. In Sprint 2 we aim to have one fully functioning general mob, which matches the guidelines given by the Design Committee. This mob will be able to spawn in waves during the gameplay and will follow the lanes given. We will also fully implement the `MobAttackTask` (previously named `ShootTask`), which will either shoot projectiles if it is far from a tower, or will perform a close-range melee attack. When taking damage, should the mobs reach 0 health we will implement a dying action and they will be removed from the game and drop currency for the player to collect. Finally, we will implement the different assets for the first mob, which include different PNGs as it takes damage, shoots projectiles, attacks and dies.

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.
- [x] #79
- [x] Mobs spawning in waves and in the lanes
- [x] Mobs dying and being removed from the game, then dropping currency
- [x] Mobs assets changing when attacking at close range, shooting projectiles and dying

# **Dependencies**
In Sprint 2, we will be working closely with a number of teams, integrating work they have already done into our General Mobs feature. 
- [x] Implement the projectiles into the `MobAttackTask`, created by Team 1 (also talk with Team 2 who have this feature implemented also)
- [x] Implement the dying and randomised currency drop with Team 3

# **Milestones**
- [x] Mobs shooting projectiles when in range of a tower (Sept. 4)
- [x] Mobs performing close-range melee attacks when they reach a tower (Sept. 6)
- [x] Mobs spawning in waves and in the lanes (Sept. 7)
- [x] Mobs assets changing when performing different tasks (Sept. 9)

**Completion Deadline:** Tuesday Sept. 12th at 3pm

# **Extras**
- [ ] Sound effects when the mobs spawn, attack and die
- [ ] The creation of additional types of mobs, once the first one is fully functioning

# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2023-studio-3/wiki/General-Mobs)
- [Testing Plan](https://github.com/UQcsse3200/2023-studio-3/wiki/General-Mobs-Testing-Plan)

# **Members**
- Megan Roxburgh (@meganroxburgh )
- Blair Cannon (@BlairCannon97 ) 
- Max Taylor (@max9753 )
- Sam Sullivan (@samsully )
- Miles Bojorge (@bojyyy )
