### ISSUE TITLE
[Team 4] MobAttackTask Class

### ISSUE THREAD

**Issue by meganroxburgh** [UQcsse3200/2023-studio-3#77]
# **Description**
**Task:** [MobAttackTask Class](#3).
**Feature:** [General Mobs Improvement ](#76)

This task will extend the work previously done on the `ShootTask` class. This task will be assigned to general NPC mobs and will constantly check how far away they are from the closest tower to them in their current lane. If they are immediately in front of a tower, a randomised weapon will be picked and the `TouchAttackComponent` class will be called to attack the tower. If they are some distance away from the tower, they will shoot a randomised projectile at the tower. Both of these attack actions will cause the tower to take damage.
 
## **Example (optional)**
- Different mobs may have different abilities (projectiles and weapons) that can either be randomised, or set to particular defaults. Based on the abilities the Enemy has, it will select the correct weapon to attack the target with based on the distance to the target.

# **Dependencies**
- [x] Work with the projectiles team to implement their base class (also consult with towers team as they have already implemented this feature)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement the existing projectiles class to shoot projectiles when the player moves in range of the mob (Sept. 2)
- [x] Wiki documentation for implementing the projectiles (Sept. 11)
- [x] Shoot Projectile when in range of a tower (Sept. 3)
- [x] Implement the melee attack when directly in front of a tower (Sept. 4)
- [x] Wiki documentation for melee attack (Sept. 11)
- [x] Tidy all wiki documentation and combine any relevant details (Sept. 11)
 
**Completion Deadline:** Monday Sept. 11th
 
# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2023-studio-3/issues/76)
- [General Mobs Wiki Documentation](https://github.com/UQcsse3200/2023-studio-3/wiki/General-Mobs)
 
# **Member**
- Megan Roxburgh (@meganroxburgh )
- Sam Sullivan (@samsully )
