### ISSUE TITLE
[Team 2] Towers and Engineers Feature Ticket

### ISSUE THREAD

**Issue by Mohamad11Dab** [UQcsse3200/2023-studio-3#78]
# **Description**
In this sprint, the focus is on implementing new features to make the game more dynamic and engaging. We are introducing 'Engineer Entities', which will add a new layer to the defense mechanism of the game. The engineers will actively participate in attacking the mobs after a lane is cleared of towers. Additionally, different types of towers will be introduced, each with their unique strengths and weaknesses in terms of armor and projectile effectiveness. The third feature will focus on enabling players to upgrade existing towers in different aspects such as fire rate, health, and/or the effectiveness of the tower's projectiles.

## SubFeature
This feature is broken up into the following subfeatures:

### Engineer Entities - 2 members
Responsible for the creation, destruction, and action mechanics (shooting at mobs) of the engineer entities. The objective is that once all engineers are dead, the game is over.

### Different Types of Towers - 2 members
Involves the development of 4 distinct types of towers, each having its special strengths and weaknesses in terms of armor and projectile efficacy.

### Upgrading Towers - 1 member
Responsible for implementing the upgrade functionality for towers. Players can upgrade towers in terms of health, fire rate, and/or projectile piercing.

### Engineer Entities
Once all towers are removed from a lane, the engineers should automatically start attacking the mobs until they die, or the mobs are cleared. If all engineers die, the game ends.

### Different Types of Towers
Players can select between four types of towers to place on the map. Each will have unique animations and specific strengths and weaknesses.

### Upgrade Towers
Players can select an existing tower and choose to upgrade it by spending in-game currency. Upgrade options can be armor, health, or effectiveness of its projectiles.

# **Dependencies**

-Engineer Entities team will need to coordinate with the Mobs team for implementing the shooting and game-over mechanics (#xx).
-Different Types of Towers will have dependencies with the Interface and Map teams for placement and grid interactions (#84).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

- [x] Design and planning of Engineer Entities sub feature complete (Sep. 2)
- [x] Design and planning of Different Types of Towers sub feature complete (Sep. 2)
- [x] Design and planning of Upgrade Towers sub feature complete (Sep. 2)

****
- [x] Write code and JUnit tests for Engineer Entities sub feature (Sep. 6)
- [x] Write code and JUnit tests for Different Types of Towers sub feature (Sep. 6)
- [x] Write code and JUnit tests for Upgrade Towers sub feature (Sep. 6)

****
- [x] Testing, Debugging, Integration - Engineer Entities sub feature (Sep. 9)
- [x] Testing, Debugging, Integration - Different Types of Towers sub feature (Sep. 9)
- [x] Testing, Debugging, Integration - Upgrade Towers sub feature (Sep. 9)

****
- [x] Documentation written - Engineer Entities sub feature (Sep. 11)
- [x] Documentation written - Different Types of Towers sub feature (Sep. 11)
- [x] Documentation written - Upgrade Towers sub feature (Sep. 11)

****
**Completion Deadline:** Sep. 12

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Ahmad (@The-AhmadAA) (Ahmad Abu-Aysha)
- Alasdair (@AlasdairS4698737) (Alasdair Sinclair)
- Mohamad (@Mohamad11Dab) (Mohamad Dabboussi)
- Praneet (@praneetdhoolia) (Praneet)
- Shivam (@shiv-0831) (Shivam Garg)

**Comment by The-AhmadAA** [comment]
These features have now been implemented
