### ISSUE TITLE
[Team 1] Single-Target Projectiles

### ISSUE THREAD

**Issue by MiniSoda17** [UQcsse3200/2023-studio-3#8]
# **Description**
**Task:** [Single-Target Projectiles](#8).
**Feature:** [Projectiles](#7 )

Implementing the base mechanics for a single-target projectile. This will be the parent class of all projectiles within the game. Single-target projectiles will inherit from a `Collisions` which allow the projectile to have a hitbox and have collisions with other objects within the game. Once the projectile makes contact with a mob, it will disappear on contact. We will also be adding different fields to the single-target projectile which can be modified down the line like speed and direction. 
 
## **Example (optional)**
- **Single-target Projectile**: Will fly across the screen at a constant speed in a linear direction.

# **Dependencies**

- [x] Collisions need to be implemented for the projectile to have a hitbox and disappear on contact(#14)
- [x] Making sure that towers can create and fire projectiles (#5)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Finalise the UI, design, and effects of the projectile (Aug. 19)
- [x] Implement the design of the projectile within the game (Aug. 20)
- [x] Seeing the projectile on screen (Aug. 21)
- [x] Adding direction to the single-target projectile (Aug. 21)
- [x] Adding the speed variable to the single-target projectile (Aug. 23)
- [x] Unit testing the single-target projectile (Aug. 25)
- [x] Updating Wiki on single-target projectiles (Aug. 27)

**Completion Deadline:** Aug. 27
 
# **Documentation**
- [Main description of feature](../wiki/Game-Features)
- [JavaDoc](https://uqcsse3200.github.io/2023-studio-3/)
- ...
 
# **Member**
- Isaac Arli (@MiniSoda17) (Isaac Arli)
- Wing Yan Lee (@cindyle1) (Cindy)
- Josephine Wong (@JSLLW) (s4528565@student.uq.edu.au)
