### ISSUE TITLE
[Team 2] Engineers Task Ticket

### ISSUE THREAD

**Issue by praneetdhoolia** [UQcsse3200/2023-studio-3#80]
# **Description**
**Task:** [[Team 2] Engineers Task](80)
**Feature:** [[Team 2] Towers and Engineers Feature Ticket](78)

This task proposes the creation of an 'Engineer' entity, a new crucial component of the game mechanics which ties in to the win/lose state of the game. The number of engineers left is a direct representation of 'HP' of the player, and if reduced to zero, ends the game. Engineer entities will spawn as described in the Logic section below. The engineers will be able to move up and down along the lanes behind the towers and attack enemy mobs using a ranged weapon. They cannot be revived, causing the user to lose the game if all engineers are dead. This feature may be extended in future sprints to allow buffing or repairing of towers, and may become controllable by the player, adding a more interactive real-time component to the game.
 
## **Logic**
One Engineer would be automatically assigned to defend a lane which satisfies the conditions below.
- The lane doesn't have any active towers.
- The defense has spare Engineer entities.
- The lane has one or more incoming mobs.

If an engineer is killed in action and the lane still meets those conditions, another would be assigned.

# **Dependencies**
- [x] [[Team 1] Working Projectile Factory.](7)
- [ ] [[Team 3] Eight fixed lanes on the map.](73)
- [x] [[Team 4] Mobs attacking other entities.](77)
- [x] [[Team 4] Mob waves and spawning in lanes.](76)
- [x] [[Team 5] Win/Lose state tracking of the game.](#132)
- [x] [[Team 5] Area effects](#95)
 
# **Milestones**
- [x] Implementation of Engineer entity factory mechanism. (Sep. 2)
- [x] Creation of Engineer entities. (Sep. 2)
- [x] Automated task logic, including mob detection and spawning. (Sep. 5)
- [x] Adding visual assets and animation controller. (Sep. 5)
- [x] Adding audio assets. (Sep. 5)
- [x] Creation of an animation controller class. (Sep. 5)
- [x] Integration of engineers into win/loss state. (Sep. 7)
- [x] Testing the Engineer entity and fixing bugs. (Sep. 7)
- [x] Integrating fully working Engineer in main. (Sep. 9)
- [x] Detailed Engineer documentation on wiki. (Sep. 11)
 
# **Optional** - May be carried over into future sprints
- [x] Implementation of engineer attacking.
- [x] Implementation of engineer damage and death.
- [ ] Integration of engineer Area Effects on Towers.
- [ ] Clickable/controllable engineers.

**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Engineer Factory](https://github.com/UQcsse3200/2023-studio-3/wiki/Engineer-Factory)
- [Engineer Combat Task](https://github.com/UQcsse3200/2023-studio-3/wiki/Engineer-Combat-Task)
 
# **Members**
- Ahmad (@The-AhmadAA) (Ahmad Abu-Aysha)
- Praneet (@praneetdhoolia) (Praneet)

**Comment by praneetdhoolia** [comment]
Added dependency links.

**Comment by The-AhmadAA** [comment]
Updated task ticket with details of the feature's role in the game, and added further tasks.
