### ISSUE TITLE
Multiple Weapon Towers Feature

### ISSUE THREAD

**Issue by shiv-0831** [UQcsse3200/2023-studio-3#81]
# **Description**
**Task:** [Multiple Weapon Towers](3)
**Feature:** [[Team 2]Towers and Engineers Feature Ticket](78)

This task promotes the creation of new tower entities which will shoot different types of projectiles and have different effect on mobs(burn, slow, knock-back, and stun). Since all towers will have different strengths and weaknesses in terms of armour and attack type/damage, the implementation of this task will add a strategic element into the game.

# **Dependencies**

- [Team 1 ] Projectile Components for Towers (#84)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Designing and planning of different types of Towers (Sep. 2)
- [x] Constructing entities and assigning components (Sep. 4)
- [x] Constructing animation controllers for implemented Towers (Sep. 6)
- [x] Integrating projectiles with towers (Sep.8)
- [x] Testing, Debugging and integration (Sep. 10)
- [x] Writing documentation (Sep 11)
 
**Completion Deadline:** Sep. 12

# **Documentation**
- [Tower Factory](https://github.com/UQcsse3200/2023-studio-3/wiki/Tower-Factory)
- [JavaDoc](https://uqcsse3200.github.io/2023-studio-3/com/csse3200/game/entities/factories/TowerFactory.html)
- ...
 
# **Member**
- Mohamad (@Mohamad11Dab) (Mohamad Dabboussi)
- Shivam (@shiv-0831) (Shivam Garg)
