### ISSUE TITLE
Team 4, General Mobs Animation Components for General Mobs

### ISSUE THREAD

**Issue by BlairCannon97** [UQcsse3200/2023-studio-3#82]
# **Description**
**Task:** Animation components for general mobs.
**Feature:** General Mobs

General mob animations which will act as important visual indicators of the mobs current behavior or status. This task will involve adding additional listeners to the existing `XenoAnimationController `class which will trigger animations for melee and ranged attacks, hurt animations and a dying animation. 
Melee animations from `xeno-grunt-melee-attack.png` will trigger once a mob reaches a tower, and serve as a indication that the tower is taking damage. The ranged attack animations from `xeno-grunt-range-attack.png` will trigger at a point consistent with the spawning of a projectile. When the health of a mob reaches 0, it will play death animation `xeno-grunt-death.png`, before it disappears.

# **Dependencies**

- [x] Projectile timing and behavior will depend on the base functionality projectile from Team-1-Tower-Projectiles 
- [x] The size of the enitity will depend on the size of the map lanes from Team-3-Maps
 
# **Milestones**

- [x] Ranged attacks trigger when ShootTask is triggered. (Sept. 4)
- [x] Melee attack animations trigger when an AttackTask is triggered (Sept. 6)
- [x] A death animation is played when the mob health has reached 0 and before it is removed (Sept. 8)
- [ ] A new hurt animation replaces the normal running animation once the mobs health falls below a certain threshold (Sept. 10)
- [x] Modify the Xeno hitboxes to better suit the gameplay
 
**Completion Deadline:** Tuesday Sept. 12th at 3pm
 
# **Documentation**
- [General Mobs Wiki](https://github.com/UQcsse3200/2023-studio-3/wiki/General-Mobs)
- [Feature Ticket](https://github.com/UQcsse3200/2023-studio-3/issues/76)
 
# **Member**
- Blair Cannon (BlairCannon97)
