### ISSUE TITLE
[Team 1] Projectile Effects

### ISSUE THREAD

**Issue by JSLLW** [UQcsse3200/2023-studio-3#83]
# **Description**
**Task:** [Projectile Effects](#3).
**Feature:** [Projectiles](#2)

Implementation of several projectile effects. The effects to be implemented are burn, slow, stun and knockback to affect the "enemies" of the "shooter". The burning effect should affect the "enemy/ies" for a duration of time upon contact. The slowing affect should affect the speed of the "enemy" it hits. For towers, this should decrease the frequency of the projectiles or decrease the speed of the projectiles they are shooting. For the stun effect, basically the target will be in active for a duration of time upon contact with the projectile but won't take any damage from the stun projectile. Finally, we will be implementing a knockback effect that will push back the mobs it comes into contact with. 

# **Dependencies**

- [ ] The health/durability of the mobs and towers (#3 )
- [ ] Collision for the projectiles (#3 )
- [ ] [Projectile animations](#74)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement a way for the projectiles to affect the entity it comes into contact with (Sep. 6) (@JSLLW)
- [ ] Implementation of projectile with burning effect (Sep. 7) (@gregchan550)
- [ ] Implementation of projectile with slowing effect (Sep. 7) (@gregchan550)
- [ ] Implementation of projectile with stun effect (Sep. 7) (@JSLLW)
- [ ] Implementation of projectile with knockback effect (Sep. 9) (@JSLLW)
- [ ] Test the different effects (Sep. 10)
- [ ] Documentation for the different effects and how to use them (Sep 11)
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
- [Main description of feature](../wiki/Game-Features)
- [User documentation](../wiki/User-Documentation)
 
# **Member**
- Jo Wong (@JSLLW) (s4528565@student.uq.edu.au)
- Gregory Chan (@gregchan550) (Gregory)
