### ISSUE TITLE
[Team 1] Projectiles Variations

### ISSUE THREAD

**Issue by MiniSoda17** [UQcsse3200/2023-studio-3#84]
# **Description**
For the second sprint, we will be building upon the base of our projectiles. Adding more variety and animation effects, and having different collision types. We will be implementing multiple types of effects for our AOE and single target projectiles i.e. slowing, knockback, stun and burning effects. We will also be implementing a new type of ability called Lane Fire Effect which will set the entire lane on fire and damage all mobs within it.

### Collision variations - @freshc0w 
[Separating different types of projectiles to have different collision mechanics](https://github.com/UQcsse3200/2023-studio-3/issues/87)

### Projectile animations - @cindyle1 & @MiniSoda17 
[Adding animations to all the projectiles within the game](https://github.com/UQcsse3200/2023-studio-3/issues/74)

### Projectile Effects- @gregchan550 & @JSLLW 
[Adding the base mechanics for AOE effects within the game](https://github.com/UQcsse3200/2023-studio-3/issues/83)

## **Examples**
- **Projectile Collision Variations**: There will be multiple types of projectiles all with their own set of collision rules like from towers and from mobs
- **Projectile effects**: Projectiles will have unique effects like slowing effect and knockback effect

# **Dependencies**

- [x] The mob attacks need to be implemented to test whether the desired effects are applied to towers ([MobAttackTask Class](https://github.com/UQcsse3200/2023-studio-3/issues/77))
- [ ] Implementation of towers needed for testing ([Multiple Weapon Towers](https://github.com/UQcsse3200/2023-studio-3/issues/81))

# **Milestones**

- [ ] [Animation of Projectiles](https://github.com/UQcsse3200/2023-studio-3/issues/74) (Sep. 11)
- [ ] [Projectile collision mechanics and variations](https://github.com/UQcsse3200/2023-studio-3/issues/87) (Sep. 9)
- [ ] [Projectile Effects](https://github.com/UQcsse3200/2023-studio-3/issues/83) (Sep. 9)
- [ ] Finalise all documentation on the wiki (Sep. 11)
- [ ] Finalise all testing (Sep. 11)

**Completion Deadline:** Sep. 12

# **Extras (optional)**
- [ ] Creating arching projectile

# **Documentation**
- [Main description of feature](../wiki/(Tower-and-Mob)-Projectile-Mechanics)
- [User documentation](../wiki/User-documentation)

# **Members**
- Isaac Arli (@MiniSoda17) (Isaac Arli)
- Chia-Chuan Tsou (@freshc0w ) (Chia-Chuan Tsou)
- Wing Yan Lee (@cindyle1 ) (Cindy)
- Gregory Chan (@gregchan550) (Gregory)
- Josephine Wong (@JSLLW ) (s4528565@student.uq.edu.au)
