### ISSUE TITLE
[Team 2] Tower upgrade task ticket

### ISSUE THREAD

**Issue by AlasdairS4698737** [UQcsse3200/2023-studio-3#86]
# **Description**
**Task:** [Tower upgrade task ticket](#86).
**Feature:** [Towers and Engineers Feature Ticket](#78)

In this sprint, a new component will be developed for the tower entity, the TowerUpgraderComponent. When an event is triggered for the tower (by the upgrade menu when it is implemented), this component will handle changing the tower's stats to implement the upgrade in-game.

# **Dependencies**
- [ ] Creation of an upgrade menu to send events to TowerUpgraderComponent (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement attack upgrade capability (Sep. 4)
- [x] Implement maximum HP upgrade capability (Sep. 6)
- [x] Implement firerate upgrade capability (Sep. 8)
- [ ] Final code cleanup and junit test checking (Sep. 10)
 
**Completion Deadline:** Sep. 12

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Alasdair (@AlasdairS4698737) (Alasdair Sinclair)
