### ISSUE TITLE
[Team 1] Collision Mechanics

### ISSUE THREAD

**Issue by freshc0w** [UQcsse3200/2023-studio-3#87]
**Task:** [Collision Mechanics](#87).
**Feature:** [Projectile Variations](#84)

Implementing several collision mechanisms for the `Projectile` entity class. In addition to its damaging and self-destructing mechanics upon collision, it should also be able to pierce through enemies while applying a certain effect/damage. The projectile could also bounce off collision and either ricochet randomly or have a chase target to other mobs/enemies. Further possible extensions of the task could include splitting projectiles upon impact, or applying a certain recoil/knockback to enemies.

# **Dependencies**
- [x] Will heavily depend on projectile effects so that effects can be tested upon collision. (#83)
- [x] Map team, understanding the boundaries of the grid, so that projectiles may also 'bounce' off these boundaries.
- [x] Collaborate with projectile animations so colliding effects can take place. (#74)
 
# **Milestones**
- [x] Finalise basic mechanics of self-destruction and damaging, ensuring it's all working on not just mob types, but enemy types. (Sep 6)
- [x] Initialise pierce mechanic and figure out a way for ricochet to happen at a basic level. (Sep 7)
- [x] Finalise ricochet concept and begin testing for both mechanics - Includes at the very least randomized direction with map bounds accounted for. (Sep 9)
- [x] Begin testing (Sep 10)
- [x] Finalise testing and write documentation (Sep 11)
 
**Completion Deadline:** Sep 12.
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Chia-Chuan Tsou (@freshc0w) (Chia-Chuan Tsou)
