### ISSUE TITLE
[Team 4] Mob waves and lane spawning

### ISSUE THREAD

**Issue by bojyyy** [UQcsse3200/2023-studio-3#89]
# **Description**
**Task:** Mob waves and lane spawning(#89).
**Feature:** General Mob Improvements (#76)

This task will extend the functionality of mob spawning. The progress made from the first sprint spawns mob in only a single wave at the beginning of the game. The aim of this task is to have mobs spawning at set intervals, and also have the spawning properly integrated with the lanes of the map. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Complete design of any new methods/classes (Sep. 5)
- [x] Implement functionality (Sep. 7)
- [x] Implement JUnit tests to verify functionality (Sep. 9)
- [x] Integrate with main branch and complete documentation (Sep. 10)

# **Documentation**
- [General Mobs Wiki](https://github.com/UQcsse3200/2023-studio-3/wiki/General-Mobs)
- [Feature Ticket](https://github.com/UQcsse3200/2023-studio-3/issues/76)
 
# **Member**
- Miles Bojorge (@bojyyy) (Miles Bojorge)
