### ISSUE TITLE
[Team 2] Towers' Graphics and sound Task

### ISSUE THREAD

**Issue by The-AhmadAA** [UQcsse3200/2023-studio-3#9]
# **Description**
**Task:** Towers' Graphics and sound
**Feature:** [Team 2] Towers Feature Ticket #5 

Implementation of the Tower Entity Graphics and sound such as visual rendering (static and animated), sound effects and cues. Selection and incorporation of visual and audio assets into the feature. The handling of updating the visual elements and sounds with events such as firing, taking damage, and destruction. 

The implementation of this task involves creation of a TowerAnimationController class, addition of tower animations to an AnimationRenderComponent in the tower instantiation method in the TowerFactory class. The triggering of these animations occurs by a task or tasks added to a tower AiTaskComponent which triggers events that start animation sequences. The packing of Textures into atlas files for use in LibGDX is also a part of this process.
 
## **Examples**
- Tower under construction images and animation to be displayed when tower in construction phase
- Tower firing images and animations when tower is firing upon enemies
- Images and animations for tower being hit and sustaining damage when being attacked by mobs
- Tower destruction images and animations when tower health reaches zero

# **Dependencies**
- [x] Task #6 Tower Entity Creation (for rendering and sound of tower placement and destruction)
- [x] Task #7 Projectiles (for sound and animation related to firing) 
- [x] Task #4 General Mobs (for sound and animation related to taking damage)
- [x] Task #10 Boss Mobs (for sound and animation related to taking damage)
- [x] Task #37 Tower Physics (for events to trigger animations)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design and Plan Graphics and sound Task (Aug. 20)
- [ ] Write JUnit tests for Graphics and sound Task (Aug. 20)
- [x] Write render component for tower entity (Aug. 23)
- [x] Select and source assets for the Graphics and sound (Aug. 23)
- [x] Integration, Testing and Debugging (Aug. 26)
- [x] Documentation Completed (Aug. 28)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Graphics](https://github.com/UQcsse3200/2023-studio-3/wiki/UI)
- [Animations](https://github.com/UQcsse3200/2023-studio-3/wiki/Animations)
- [Sound](https://github.com/UQcsse3200/2023-studio-3/wiki/Audio)
 
# **Member**
- Ahmad (@The-AhmadAA) (Ahmad Abu-Aysha)

**Comment by The-AhmadAA** [comment]
Updated with dependencies, milestones and deadlines.

**Comment by The-AhmadAA** [comment]
Updated deadlines for planning and JUnit test completion due to delays and added dependency on Tower physics

**Comment by The-AhmadAA** [comment]
Added implementation details.

**Comment by The-AhmadAA** [comment]
Added Animations for idle, stow, deploy and firing, and events to trigger via a AITaskComponent Task.

**Comment by The-AhmadAA** [comment]
Added Sound assets and triggering for weapon tower. 
Added a walltower sprite, walltowers can now be spawned and are visible.
Replaced the ForestGameArea bgm to be more in line with the Sci-Fi theme.

**Comment by The-AhmadAA** [comment]
Added more sound assets and triggering for deploy and stow states, fixed firing sound bug.

**Comment by The-AhmadAA** [comment]
Sprint 1 graphics and sound functionality complete, documentation almost done, attempting to write some JUnit tests specific to functionality in this ticket

**Comment by The-AhmadAA** [comment]
Base functionality implemented
