### ISSUE TITLE
[Team 4] Mob Death & Currency Dropping.

### ISSUE THREAD

**Issue by max9753** [UQcsse3200/2023-studio-3#90]
# **Description**
**Task:** Mob Death & currency dropping for dead mobs.
**Feature:** General Mobs

This task is to ensure that a mob dies when its' health reaches zero. A mob will be hurt by projectiles until its health reaches zero, upon reaching zero the mob will have a death animation (implemented in another task), the mob will be disposed of from the players screen and finally the mob will drop a currency in place for the player to collect by clicking on it.

This will be a very important part of the characteristics of mobs in the game as they will be useful when killed to increase the players currency levels.

# **Dependencies**

- [x] Currency system with methods to spawn currency or more than one currency.
- [x] Mob death animation being implemented.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Mob death is registered when mob health reaches zero. (Sept 4th)
- [x] Mob is disposed from players screen. (Sept 6th)
- [x] Mob has animated death. (Sept 7th)
- [x] Mob drops currency on death for player to collect. (Sept 9th)
- [x] Feature merged with main (Sept 10th) 
- [x] Wiki documentation completed (Sept 10th)
 
**Completion Deadline:** Sept 12th 15:00.
 
# **Documentation**
- [General Mobs Wiki](https://github.com/UQcsse3200/2023-studio-3/wiki/General-Mobs)
- [Feature Ticket](https://github.com/UQcsse3200/2023-studio-3/issues/76)
 
# **Member**
- Max Taylor (@max9753) Max Taylor.
