### ISSUE TITLE
[Team 5] Tower placement

### ISSUE THREAD

**Issue by ryandmcneilly** [UQcsse3200/2023-studio-3#93]
THIS TICKET HAS BEEN CLOSED (SEE #108)

# **Description**
**Task:** Tower Placement (#93).
**Feature:**  (#96).

This task will focus on setting up the tower placement, that is giving the user an interface for users to place towers on the map. This functionality will include lowering the amount of currency the user has by the appropriate amount, and checking if such a placement is valid. This will involve a lot of communication with the Interface team, as placement and design will play an important part in the task.  We are extending (#35). 

## **Example (optional)**
- **Interface**: This task will provide an interface to the user allowing the user to drag and drop different towers onto the map in exchange for currency.

# **Dependencies**
- [ ] The grid layout of the map is suitable for the turret placement. 

# **Milestones**
List of steps that need to be completed for this task.
#### Goal 1 (Sep 6): Planning and Scaffolding 
- [ ] Design of the menu that players can choose turrets from
- [ ] Planning required methods needed (if any) for the class

#### Goal 2 (Sep 11) Code Implementation 
- [ ] Implement the turret menu
- [ ] Write a function that checks if a tile would be a valid placement 
- [ ] Implement the drag and drop feature, utilising the above function, so that a turret can be dragged and placed on a tile on the game. Also, make sure currency gets decremented.

#### Goal 3 (Sep 12) Testing and Debugging (JUnit); Integration
- [ ] Design and implement a testing suite
- [ ] Debug faulty code
- [ ] Implement interaction with currency functionality

#### Goal 4 (Sep 12) Documentation
- [ ] Document code and testing suite
 
# **Documentation**
- TBD
 
# **Member**
- Ryan (@ryandmcneilly ) (Ryan McNeilly)
- Nawal (@nawal-0) (Nawal)

**Comment by Hasakev** [comment]
This ticket has been closed and will be done in #108
