### ISSUE TITLE
[Team 5] UI Implementation and Design of WInning/Losing Scenarios

### ISSUE THREAD

**Issue by SonjaMcNeilly** [UQcsse3200/2023-studio-3#94]
# **Description**
**Task:** (#94).
**Feature:** (#96)

The aim of this task is to implement the initial UI and design the UI of the scenarios where the player loses the game, or wins the game based on winning and losing conditions. The assets in designing the menus and explosion on screen will come from asset packs. 
 
## **Example (optional)**
- **Losing Scenario**: Implement an explosion on the screen, then pop up with a menu asking to play again, go back to menu or quit game.
- **Winning Scenario**:  Text will pop up with saying 'You Won!' then have a menu fade providing the options to play again, go back to menu or quit game.

# **Dependencies**
No dependencies this sprint.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Put the explosion animation on screen on loss condition (Sept. 8)
- [x] Design menu screen for winning and losing conditions (Sept. 9)
- [x] Put menu on the screen after explosion (losing condition) (Sept. 10)
- [x] Put "You Won!" on winning condition and put menu screen on screen (Sept. 11)
 
**Completion Deadline:** Sept. 12
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Sonja McNeilly (SonjaMcNeilly) (Sonja McNeilly)
