### ISSUE TITLE
[Team 5] Map Grid and Area of Effect on entities

### ISSUE THREAD

**Issue by Hasakev** [UQcsse3200/2023-studio-3#95]
# **Task Ticket: Map Grid and Area of Effect on Entities**

**Task:**  Implementation of the map grid and AOE component class on entities.
**Feature:** #96 

This is an extension of the feature ticket, #25 

## **Description**
The implementation of #93 and Area of effects relies heavily on the implementation of the map grid. This task will look to create a basic grid class that all entities will be placed on. Each lane on the map grid will be independent of each other in terms of mobs and interaction (this is subject to change)

We will need to interact with the GameArea files and communicate with Team 3 for this feature.

The AOE effect will be implemented after the map grid which will be a component that can be added to any entity (i.e. turrets or engineers) such that any entity in a 1 tile radius of the entity receives a temporary "buff". This will be heavily reliant on the implementation the grid. 

## **Example**
This is the map grid where enemy mobs traverse, turrets are placed and where everything will operate. 

The AOE effect will provide temporary buffs to nearby ally entities if they are within a 1 tile radius.

## **Dependencies**
The AOE class relies on the implementation of the map grid class.

## **Milestones**
List of steps that need to be completed for this task.

#### Goal 1 (Sep 6): Planning and Scaffolding 
- [ ] Plan out and communicate with other teams (specifically #25)
- [ ] Design and plan the implementation of the map class and AOE class.

#### Goal 2 (Sep 8) Code Implementation and Test Design (JUnit)
- [ ] Implement the map grid class and 
- [ ] Write JUnit tests (ensure use of mocking)

#### Goal 3 (Sep 10) Testing and Debugging; Integration
- [ ] Communicate with other teams for integration
- [ ] Test map grid with other entities in other teams for bugs and issues

#### Goal 4 (Sep 11) Documentation
- [ ] Document the implementation details of the map grid and AOE feature.
- [ ] Update relevant documentation to reflect the changes made.

**Completion Deadline:** Sep. 12

> If time is still available, improve the currency classes i.e. animations and bugfixes

## **Documentation**
- TBA

## **Member**
- Kevin (@Hasakev) (Kevin Luo)
- Jackie (@fattyhope) (Jackie)

**Comment by Hasakev** [comment]
This ticket was completed in (#40) but due to miscommunication, this was duplicated. AOE was completed by @Mohamad11Dab  (Thanks)
