### ISSUE TITLE
[Team 5] UI

### ISSUE THREAD

**Issue by Hasakev** [UQcsse3200/2023-studio-3#96]
# **Description**
Our team has implemented the economy system last sprint, this includes:
- Income Tower
- Global income system (using Service)
- Mob Drop
- UI display of Income

This sprint, our team is looking to interact and collaborate with team 6 to complete UI tasks. We are also looking to improve the existing currency system. Here are our proposed tasks:
- ~~Tower placement~~
- Win/Loss conditions
- ~~Map grid and AOE effects~~
- Further quality of life changes to existing economy features

## Sub Features/Component 
Each member will be responsible for one of the following components:
- ~~Tower placement~~
- UI implementation and design of winning/losing scenarios 
- ~~Map grid and area of effect~~
- Quality of life changes to current economy system 

## **Examples**
- ~~**UI**: The UI will display a tower which can be dragged and placed on the map~~
- **Win Condition UI**: The display will "explode" when the player loses or display a victory screen when the player wins.
- ~~**Area of effect**: This component can be added to any entity and provides "buffs" to entities within a 1 tile radius.~~

# **Dependencies**
This ticket relies on the completion of all subfeatures (task tickets):
- ~~Tower placement (#93)~~
- UI implementation and design of winning/losing scenarios (#94)
-~~Map grid and area of effect (#95)~~
- Quality of life changes to the current economic system (#121 )
- ~~Level select screen (#111 )~~

# **Milestones**
#### Goal 1 (Sep 6): Planning and Scaffolding 
- [ ] UI implementation and design of winning/losing scenarios 
- [ ] Level select screen
#### Goal 2 (Sep 8) Code Implementation and Test Design (JUnit)
- [ ] UI implementation and design of winning/losing scenarios
- [ ] Level select screen
#### Goal 3 (Sep 10) Testing and Debugging; Integration
- [ ] UI implementation and design of winning/losing scenarios
- [ ] Level select screen
#### Goal 4 (Sep 11) Documentation 
- [ ] UI implementation and design of winning/losing scenarios
- [ ] Level select screen

**Completion Deadline:** Sep 12

# **Extras**
These features are low priority and will be implemented if ahead of schedule:
-  Second type of currency
-  Special drop animation
- Sophisticated UI

# **Documentation**
TBA

# **Members**
Ryan (@ryandmcneilly) (Ryan McNeilly)
Sonja (@SonjaMcNeilly) (Sonja)
Nawal (@nawal-0) (Nawal)
Jackie (@FattyHope) (Jackie) 
Kevin (@Hasakev) (Kevin Luo)
