### ISSUE TITLE
[Team-3]Map Background

### ISSUE THREAD

**Issue by Moksh-Mehta7** [UQcsse3200/2023-studio-3#99]
# **Description**
**Task:** [Map Background](#3).
**Feature:** [In game map background will be implement](#2)

A static image will be set as single cell in the background tiles , grid and lanes will be placed on top of it.
 

# **Dependencies**
Design ideas from design community 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Selecting Image for the background (Sep. 2)
- [x] Editing and getting a desired dimension (Sep. 3)
- [x] Implementing and adding image to the game  (Sep. 6)
- [x] Final editing(Sep. 8)

 
**Completion Deadline:** 
12 Sep 2023
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Moksh( @Moksh-Mehta7 )(Moksh Mehta)
